// File: data2.js
const novelData2 = [
    { 
        title: "Bab 3: Hari ke-28 — Menahan Diri di Tengah Hujan", 
        content: `
            <p>Dua puluh delapan hari. Kurang dari sebulan sejak garis batas itu bergeser secara diam-diam di gazebo SMAN 90 Bandung. Selama rentang waktu itu, ritme hidup Sakra terbagi menjadi dua dunia yang saling bertolak belakang: siang hari yang bising di lingkungan sekolah, dan malam hari yang sunyi di balik layar monitor tempat ia merajut asa lintas kabupaten bersama Tasya di SMAN 81 Pangandaran.</p>
            <p>Hari itu, langit Bandung menunjukkan tabiat buruknya sejak matahari bergeser ke barat. Pukul tiga sore, awan kumulonimbus berwarna kelabu pekat menggantung rendah di atas atap-atap gedung sekolah, menutupi sisa-sisa cahaya biru kemerahan. Udara mendadak terasa lembap, berbau tanah basah yang diangkat angin dari hamparan rumput lapangan.</p>
            <p>Di dalam sanggar Pramuka SMAN 90 Bandung, suasana tidak kalah runyam.</p>
            <p>Sakra sedang duduk bersila di dekat meja kayu panjang, memegang sebuah <em>flashdisk</em> hitam berukuran kecil di antara ibu jari dan telunjuknya. Di hadapannya, Dimas—anggota junior MDC yang dikenal sering ceroboh dan hobi menghindar dari tanggung jawab—berdiri sambil menggigit kuku, memasang wajah pucat pasi.</p>
            <p>"Maksud lo apa, Dim? <em>Flashdisk</em> data rekapitulasi inventaris ambalan dan arsip digital kelas sepuluh yang kemarin dititipin ke lo... sekarang ilang?" suara Sakra terdengar tenang, namun nadanya sedingin es. Tidak ada bentakan, tidak ada nada tinggi. Justru ketenangan itu yang membuat Dimas semakin ketakutan.</p>
            <p>"S-sumpah, Kak Sakra... kemarin pas pulang latihan, tak taruh di dalam saku tas ransel. Tapi tadi pas tak cari di rumah, tasnya kosong, kayaknya jatoh di sekitar sanggar atau kantin..." cicit Dimas gemetar, keringat dingin bercucuran di pelipisnya.</p>
            <p>Sakra menghela napas panjang. Ia menutup matanya sejenak, meredam gelombang emosi yang mendadak mendesak naik ke dadanya. Bagi seorang Ketua MDC yang sangat menjunjung tinggi keteraturan data, kehilangan <em>flashdisk</em> berisi <em>backup</em> arsip penting tanpa salinan <em>cloud</em> yang mutakhir adalah sebuah pukulan telak. Tengkorak kepalanya mendadak berdenyut nyeri. Masalah ini tidak boleh dibiarkan begitu saja; jika data itu tidak ditemukan, ia harus merelakan waktu semalaman untuk menyusun ulang seluruh lembar rekap dari nol sebelum laporan diserahkan ke pembina esok pagi.</p>
            <p>Sebelum Sakra sempat melontarkan teguran yang lebih telak, suara dentuman guntur membelah langit angkasa dengan garang.</p>
            <p><em>Bummmm!</em></p>
            <p>Detik berikutnya, langit Bandung benar-benar runtuh. Air hujan tumpah ruah dalam skala masif, menghantam atap seng sanggar Pramuka dengan suara gemuruh yang memekakkan telinga. Angin kencang bertiup liar, menerbangkan debu dan menepiskan air hujan hingga membasahi lantai teras sanggar. Bau petrikor yang tajam menyeruak, beradu dengan aroma lembap kayu tua ruangan tersebut.</p>
            <p>"Udah, urusan si Dimas lu pending dulu, Kra. Nih <em>flashdisk</em> bisa dicari lagi nanti, tapi kalau lu berdiri terus di situ muka lu bisa pucat pasi kayak mayat," sergah suara serak dari ambang pintu.</p>
            <p>Indra dan Habib muncul dari balik tirai air hujan, berlari kecil menerobos amukan badai dengan seragam Pramuka yang basah di bagian bahu. Habib membawa sebungkus kantong plastik putih berukuran sedang, sementara Indra langsung menutup pintu kayu sanggar rapat-rapat untuk menghalau cipratan air.</p>
            <p>"Gila, badai dadakan Bandung mah emang nggak ngotak!" cibir Indra sambil mengibas-ngibaskan ujung lengan bajunya yang basah. Ia melempar handuk kecil ke meja, lalu melirik tajam ke arah Dimas. "Lu masih di sini, Dim? Mau meluk tiang? Sana minggat dulu, biarin Ketua MDC kita lagi pusing mikirin data lu yang lenyap. Besok pagi lu harus sudah bawa kabar atau gua aduin ke Kak Nisa!"</p>
            <p>Tanpa buang waktu, Dimas langsung kabur meninggalkan sanggar, memanfaatkan kesempatan dalam kesempitan.</p>
            <p>Meski Dimas sudah pergi, rasa kesal di dada Sakra belum sepenuhnya menguap. Kepalanya masih berdenyut memikirkan konsekuensi dari hilangnya arsip tersebut. Namun, sebelum ia sempat membuka laptop untuk memeriksa salinan lama di direktori lokal, Habib melangkah mendekat dan membuka kantong plastik putih yang dibawanya.</p>
            <p>Habib mengeluarkan tiga mangkuk plastik berisi batagor hangat berkuah kacang kental yang mengepulkan uap putih. Bau gurih kacang tanah dan jeruk limau langsung memenuhi ruangan yang tadinya berbau lembap.</p>
            <p>"Nih, buat nyuci otak lu yang lagi pening gara-gara si Dimas ceroboh," kata Habib menyodorkan semangkuk batagor ke hadapan Sakra. "Makan dulu, Kra. Masalah data ilang emang bikin stres, tapi perut kosong bakal bikin lu makin gila."</p>
            <p>Sakra menatap mangkuk batagor itu sekilas, lalu mengusap wajahnya dengan kedua tangan. Ia sadar, memandangi meja kosong tidak akan mengembalikan <em>flashdisk</em> itu seketika. Dengan gerakan lesu, ia menarik mangkuk tersebut mendekat, meski pikirannya masih separuh melayang pada tumpukan tugas yang menanti esok hari.</p>
            <p>Di tengah badai sore itu, ponsel di dalam saku Sakra bergetar pelan.</p>
            <p>Sakra langsung merogoh sakunya. Layar menyala, menampilkan pesan dari Tasya yang dikirim dari Pangandaran.</p>
            <blockquote>
                <strong>Tasya:</strong> <em>“Sak... di Bandung hujan deras banget gak? Di sini anginnya kencang banget, sampai atap seng di sebelah sekolah bunyi. Sumpah serem, gue lagi sendirian di ruang OSIS nunggu jemputan mama. Lu lagi di mana? Kangen...”</em>
            </blockquote>
            <p>Membaca kata <em>kangen</em> di ujung pesan itu, pertahanan rasional Sakra mendadak mengalami guncangan. Transisi emosinya terjadi begitu cepat—dari seorang ketua organisasi yang ketat dan jengkel pada anak buahnya, seketika berubah menjadi remaja yang dihantam gelombang rindu luar biasa.</p>
            <p>Di dalam ruang sanggar yang beraroma basah, di tengah omelan kecil Indra dan Habib yang sedang melahap batagor, pikiran Sakra langsung meloncat menyeberang 179 kilometer menuju pesisir selatan Jawa Barat. Ia membayangkan Tasya di sana—duduk seorang diri di ruang OSIS SMAN 81 Pangandaran yang dingin, mendengarkan deru angin laut dan hujan badai yang menghantam jendela, tanpa ada siapa pun di sampingnya.</p>
            <p>Ada dorongan yang begitu kuat di dalam dada Sakra untuk membalas pesan itu dengan kalimat gegabah: <em>“Tunggu ya Sya, gue cabut sekarang naik bus ke Pangandaran buat meluk lu.”</em></p>
            <p>Sebuah keinginan impulsif yang lahir dari rasa cinta yang mulai mendominasi akal sehatnya. Sakra ingin melompati jarak 179 kilometer itu detik ini juga. Ia ingin berdiri di hadapan Tasya, membawakan jaket hangat, dan memastikan gadis itu tidak merasa sendirian di tengah cuaca buruk.</p>
            <p>Namun, realita langsung menamparnya telak.</p>
            <p>Jalanan Bandung menuju Pangandaran di tengah badai besar seperti ini adalah mimpi buruk. Jalur nagrek dan kawasan gentong terkenal rawan longsor saat curah hujan tinggi. Ongkos bus, waktu tempuh lima jam, serta kewajibannya sebagai siswa MDC yang esok harinya harus membereskan kekacauan data dari Dimas membuat angan-angan itu mendadak terasa begitu mustahil.</p>
            <p>Sakra terjebak di sini. Di Bandung. Di balik meja kayu sanggar yang basah.</p>
            <p>"Kra? Malah melamun. Batagornya keburu dingin tuh, kuahnya udah mulai meresap ke siomaynya," tegur Indra sambil menyumpit sepotong pangsit goreng ke dalam mulutnya.</p>
            <p>Sakra mengerjap perlahan, menarik napas dalam-dalam untuk menormalkan debar jantungnya. Ia menatap layar ponselnya, lalu mulai mengetik balasan dengan jempol yang sedikit gemetar karena menahan gejolak rindu yang teramat sangat.</p>
            <blockquote>
                <strong>Sakra:</strong> <em>“Iya, Sya, di Bandung juga lagi badai parah nih. Hati-hati di ruang OSIS, jangan keluar kalau belum dijemput mama. Kalau takut, telpon gue sekarang. Gue ada di sanggar nemenin lu lewat hp.”</em>
            </blockquote>
            <p>Tidak sampai lima detik setelah pesan itu terkirim, layar ponselnya berubah menjadi panggilan masuk dari Tasya.</p>
            <p>Sakra langsung menekan tombol hijau, mendekatkan ponsel ke telinganya di tengah suara hujan deras di luar dan suara batagor yang dikunyah Habib di dalam ruangan.</p>
            <p>"Halo, Sakra..." suara Tasya terdengar gemetar di ujung sana, bercampur dengan suara deru angin kencang yang menghantam kaca jendela SMAN 81 Pangandaran. "Gue merinding banget denger suara geledek di luar. Lampu koridor sekolah juga sempat kedip-kedip tadi."</p>
            <p>"Iya, Sya, denger nih suara hujan di Bandung juga gede banget," ucap Sakra lembut, sengaja mendekatkan mikrofon ponselnya ke arah jendela sanggar agar suara gemuruh hujan dan petir terdengar jelas di telinga Tasya. "Gue di sini, nemenin lu. Jangan takut ya."</p>
            <p>Di ujung seberang sana, Tasya menarik napas panjang, mencoba menenangkan diri. "Sak... lu tahu nggak? Tadi pas badai mulai datang, gue tiba-tiba pengen banget lu ada di sini. Rasanya capek banget harus ngelewatin cuaca jelek sendirian kayak gini."</p>
            <p>Kata-kata itu meluncur begitu jujur, menghujam langsung ke lubuk hati Sakra. Ada rasa sakit yang menyayat-nyayat dadanya—rasa sakit karena menyadari betapa kejamnya angka 179 kilometer yang memisahkan fisik mereka saat salah satu dari mereka sedang merasa rapuh.</p>
            <p>Sakra mengepalkan tangan kirinya erat-erat di atas pangkuannya. Giginya mengatup rapat, menahan beban emosional yang mendadak terasa begitu berat. Ia ingin sekali mengatakan bahwa ia akan melakukan apa saja untuk memperpendek jarak itu. Namun, ia juga sadar, ia hanyalah seorang remaja SMA biasa yang terikat oleh waktu, jarak, dan keterbatasan.</p>
            <p>"Sabar ya, Sya," bisik Sakra parau, suaranya nyaris tenggelam oleh suara hujan lebat di sanggar.</p>
            <p>Indra dan Habib yang duduk di sudut ruangan mendadak menghentikan kunyahan mereka. Mereka saling berpandangan sekilas, menangkap perubahan nada suara Sakra yang mendadak sangat serius, lembut, dan penuh beban. Indra mengisyaratkan pada Habib dengan gerakan mata agar tidak bersuara keras-keras, menghargai privasi sahabat mereka yang sedang bertarung dengan badai rindu lintas kabupaten.</p>
            <p>Malam itu, di Hari ke-28, di tengah badai hujan yang melumpuhkan Bandung dan Pangandaran, Sakra belajar arti paling pahit dari sebuah hubungan jarak jauh: terkadang, bentuk cinta yang paling besar bukanlah tentang seberapa sering kita bersama, melainkan tentang seberapa kuat kita harus <strong>menahan diri</strong> untuk tidak menerjang batas ketika semesta sedang tidak berpihak pada pertemuan. Dan esok hari, di balik sisa-sisa kelelahan itu, Sakra tahu ia masih harus menghadapi setumpuk data yang hilang di ruang MDC SMAN 90 Bandung.</p>
        `
    }
];
