// File: data16.js
const novelData16 = [
    { 
        title: "Bab 18: Hari ke-145 — Pengakuan yang Menyesakkan Dada", 
        content: `
            <p>Malam di Bandung merambat lambat, membawa sisa-sisa hawa dingin pegunungan yang menembus celah-celah jendela kamar Sakra. Jam dinding di sudut ruangan baru saja menunjuk pukul 22.15 WIB. Suasana di dalam rumah sudah lama terlelap dalam sunyi, meninggalkan Sakra seorang diri di hadapan meja belajarnya yang diterangi pendar lampu kuning remang.</p>
            <p>Sejak pesan singkat ucapan selamat ulang tahun berbalut kata <em>“sayang”</em> yang kaku beberapa hari lalu, hubungan Sakra dan Tasya seolah berjalan di atas titian es yang tipis. Ada jarak yang tidak terlihat, namun sangat terasa menusuk. Setiap kali mereka melakukan panggilan telepon, percakapan sering kali terhenti oleh keheningan yang canggung, diisi oleh helaan napas panjang atau jawaban-jawaban singkat yang dipaksakan. Sakra merasa ada sesuatu yang besar sedang disembunyikan oleh kekasihnya di seberang sana, sesuatu yang terus menggerogoti ketenangan batin Tasya tanpa ia ketahui akar masalahnya.</p>
            <p>Malam itu, keraguan dan rasa penat itu mencapai puncaknya. Sakra memutuskan untuk memecah keheningan. Ia meraih ponsel pribadinya, lalu menekan tombol panggil ke nomor Tasya. Ia butuh kejelasan; ia tidak sanggup lagi hidup dalam ketidakpastian sikap yang ditunjukkan oleh gadis yang paling ia cintai di dunia ini.</p>
            <p>Sambungan berdering empat kali sebelum akhirnya suara lembut namun terdengar sangat lelah menyapa dari ujung seberang sana.</p>
            <p>"Halo, Sakra..." sapa Tasya pelan. Suaranya serak, menyiratkan bahwa ia baru saja menangis atau setidaknya sedang menahan isak tangis yang mendesak naik ke tenggorokan.</p>
            <p>"Halo, Sya..." balas Sakra, berusaha menjaga nada suaranya agar terdengar setenang mungkin, meski jantungnya sendiri berdegup kencang diliputi kecemasan. "Lu belum tidur? Udah malem banget loh ini."</p>
            <p>"Belum... aku masih di meja belajar," jawab Tasya singkat.</p>
            <p>Keheningan kembali melanda sambungan telepon lintas kabupaten itu selama beberapa detik. Hanya suara desau angin malam dan napas berat di masing-masing ujung sambungan yang terdengar. Sakra mengepalkan tangannya di atas meja, tidak ingin terus-menerus terjebak dalam basa-basi yang menyiksa.</p>
            <p>"Sya," panggil Sakra serius, memecah keheningan malam. "Ada apa sebenarnya? Kenapa belakangan ini sikap lu ke aku jadi beda banget? Tiap kali kita ngobrol, lu kayak nutup diri, kaku, dan kayak lagi nahan beban yang berat banget di sana. Kalau aku ada salah, bilang... jangan dipendem sendiri kayak gini."</p>
            <p>Di seberang sana, sejauh 179 kilometer di kamarnya yang remang di Pangandaran, Tasya menatap nanar dinding kamarnya. Air mata yang sejak tadi ia tahan akhirnya tumpah begitu saja membasahi pipinya. Pertahanan terakhir yang ia bangun selama berminggu-minggu runtuh seketika mendengar pertanyaan tulus dari Sakra. Beban psikologis yang menghimpit dadanya sudah terlalu berat untuk ia pikul seorang diri.</p>
            <p>Tasya menarik napas panjang, mencoba meredam isakannya yang mulai lolos dari bibir.</p>
            <p>"Sak..." cicit Tasya lirih, suaranya bergetar hebat penuh kepedihan. "Bukannya aku gak mau terbuka... tapi aku udah gak sanggup."</p>
            <p>Sakra terkesiap di kursinya. Alisnya bertaut tajam. "Gak sanggup? Maksud lu apa, Sya? Siapa yang bikin lu gak sanggup?"</p>
            <p>"Aku... aku ngerasa hancur, Sak," isak Tasya akhirnya, menyerah pada air mata yang mengalir deras tanpa henti. "Tiap hari aku mikirin hubungan kita, tiap hari aku ngerasa jadi pacar yang paling gak becus di dunia ini."</p>
            <p>Sakra bangkit berdiri dari kursinya, rasa panik mendadak menyerang rongga dadanya. "Lu ngomong apa sih, Sya? Gak becus gimana? Siapa yang bilang lu gak becus?"</p>
            <p>"Diri aku sendiri, Sak!" teriak Tasya tertahan di ujung telepon, suaranya pecah diselimuti tangis histeris yang menyayat hati. "Lu inget kan apa aja yang udah lu lakuin buat aku? Lu begadang berbulan-bulan bikin <em>Project_179</em> yang megah, lu banting tulang jadi scripter MDC, lu ngasih perhatian luar biasa, dan lu selalu ngorbanin tenaga lu separuh mati demi aku..."</p>
            <p>Sakra terdiam kaku. Ia mendengarkan setiap patah kata yang diucapkan Tasya dengan napas tertahan.</p>
            <p>"Tapi aku bisa apa, Sak?" suara Tasya melemah, berubah menjadi rintihan pilu yang meremajakan hati siapa pun yang mendengarnya. "Uang jajan aku pas-pasan, keahlian aku biasa aja, waktu ulang tahun lu kemarin aku bahkan gak bisa ngasih kado apa-apa selain ucapan lewat chat. Aku ngerasa posisinya jomplang banget antara aku sama lu."</p>
            <p>Kalimat-kalimat itu meluncur begitu telak, menghujam langsung ke ulu hati Sakra.</p>
            <p>"Lu ngasih seribu, sedangkan aku... aku cuma bisa ngasih sepuluh," lanjut Tasya, isakannya semakin tak terkendali. "Aku ngerasa jomplang banget, Sakra. Aku ngerasa jadi beban buat lu. Setiap kali lu ngasih <em>effort</em> yang begitu besar, aku malah ngerasa punya utang budi yang gak bakal pernah bisa lunas. Aku bingung... aku bingung banget gimana caranya bales <em>effort</em> lu biar setara, biar aku gak ngerasa kecil di hadapan lu."</p>
            <p>Pengakuan paling jujur dan paling menyakitkan itu akhirnya terucap sudah. Di malam di Hari ke-145 itu, tirai penutup yang menutupi akar masalah hubungan mereka tersibak lebar-lebar. Selama ini, Sakra mengira bahwa memberikan segalanya—segala bentuk perhatian, karya digital, dan pengorbanan fisik—adalah wujud cinta yang paling sempurna untuk membuktikan kesetiaannya di tengah jarak 179 kilometer. Namun, ia tidak pernah menyadari bahwa bagi Tasya yang berhati lembut dan penuh rasa sungkan, bentuk cinta yang berlebihan itu justru berubah wujud menjadi beban psikologis yang sangat menekan—sebuah ketimpangan tak kasat mata yang perlahan-lahan meremajakan mental kekasihnya dari dalam.</p>
            <p>Di kamarnya di Bandung, Sakra berdiri mematung. Ponsel di telinganya terasa sangat berat. Tenggorokannya mendadak kelu, tidak mampu merangkai kata-kata untuk membela diri atau menyangkal kenyataan pahit tersebut. Air matanya sendiri perlahan menetes jatuh ke lantai kamar, menyadari betapa bodohnya ia karena mengira cinta bisa diukur dengan seberapa banyak pengorbanan yang bisa diberikan, tanpa pernah melihat apakah orang yang menerimanya sanggup memikul beban balasan tersebut.</p>
            <p>Sambungan telepon malam itu diisi oleh tangis Tasya yang pilu di Pangandaran dan kebisuan total dari Sakra di Bandung—sebuah dialog penutup yang menyayat hati, menandai babak paling kelam di mana cinta mereka mulai tergilas oleh jurang ketimpangan yang mereka ciptakan sendiri.</p>
        `
    }
];
