// File: data.js
const novelData = [
    { 
        title: "Bab 1: Hari Pertama — Garis yang Bergeser", 
        content: `
            <p>Siang itu, udara di atas lapangan SMAN 90 Bandung terasa seperti uap panas yang keluar dari mesin pembakaran. Cahaya matahari bulan April menerobos celah-celah dedaunan pohon angsana yang kusam oleh debu jalanan, menciptakan pola-pola catur cahaya yang menari-nari di atas tanah kering berdebu. Suara bel panjang penanda berakhirnya jam pelajaran terakhir baru saja mati, digantikan oleh kegaduhan seketika dari ratusan siswa yang berhamburan keluar dari ruang kelas masing-masing.</p>
            <p>Langkah-langkah kaki bersahut-sahutan di koridor semen yang memanjang. Ada jeritan melengking dari kelompok siswi kelas sebelas yang berlari riang menuju gerbang utama untuk berburu es doger di trotoar luar, ada dentuman bola basket yang dipantulkan malas di selasar lapangan olahraga, dan ada pula sekelompok anak laki-laki yang berjalan menyeret sepatu sambil memperdebatkan strategi game ponsel terbaru.</p>
            <p>Di tepi lapangan, tepat di dekat gazebo kayu beratap genteng usang yang berdampingan langsung dengan sanggar Pramuka, Sakra berdiri seorang diri.</p>
            <p>Di atas meja kayu panjang yang permukaannya dipenuhi sisa coretan tip-ex lama dan ukiran nama-nama alumni tahun lalu, Sakra sibuk menyusun tumpukan berkas biodata anggota baru. Jemarinya yang cekatan dan terbiasa mengetik cepat pada papan ketik komputer kini meluruskan sudut-sudut kertas A4 yang agak terlipat, menumpuknya dengan tingkat presisi tinggi sesuai urutan abjad nomor induk siswa. Sebagai Ketua Media Data Center (MDC) Ambalan SMAN 90 Bandung, kerapian bukan lagi sekadar instruksi pembina, melainkan sebuah bentuk kontrol mutlak yang ia sukai.</p>
            <p>Sakra menyukai keteraturan yang pasti. Dalam barisan kode HTML, CSS, fail skrip Python, hingga konfigurasi direktori Linux Ubuntu VPS yang biasa ia tulis hingga larut malam di kamarnya, dunia terasa sangat aman dan patuh. Jika ada variabel yang salah tempat, terminal akan memuntahkan pesan galat. Jika ada tanda titik koma (<em>semicolon</em>) yang hilang, program berhenti berjalan tanpa ampun. Ada sebab, ada akibat. Sistem selalu memberikan kejelasan. Tidak ada ruang untuk ambiguitas di dalam barisan kode.</p>
            <p>Ia mengambil sebuah klip besi berwarna hitam, menekan kedua tuasnya dengan tenaga pas, lalu menjepit tumpukan kertas biodata itu tepat di garis tengahnya.</p>
            <p><em>Bzzzt... Bzzzt...</em></p>
            <p>Ponsel pintar di dalam saku celana abu-abu seragam SMA-nya bergetar dua kali secara ritmis.</p>
            <p>Sakra menyapu peluh tipis yang merembes di keningnya dengan pinggiran lengan baju seragam Pramukanya yang berwarna cokelat tua—lengkap dengan atribut ambalan terssemat rapi di dada—lalu merogoh saku. Layar ponsel menyala, memunculkan jendela notifikasi yang sangat akrab di retinanya. Sebuah nama tercetak tebal di sana, nama yang dalam dua tahun terakhir selalu mendominasi daftar prioritas di ponselnya: <strong>Tasya</strong>.</p>
            <blockquote>
                <strong>Tasya:</strong> <em>“Sak, baru beres kumpul OSIS nih di SMAN 81. Capedeh pembina kesiswaan cerewet banget hari ini, minta revisi proposal pensi mulu 😭 Lu lagi ngapain di Bandung? Udah makan belum?”</em>
            </blockquote>
            <p>Sakra menatap gelembung teks berwarna hijau muda itu. Jempol kanannya melayang beberapa milimeter di atas permukaan kaca pelindung layar. Secara refleks, ingatan ototnya siap menekan papan ketik virtual untuk merangkai balasan singkat dan standar: <em>“Biasa, lagi di sanggar bereskan data. Makan sana lu.”</em> Sebuah balasan refleks yang wajar, datar, dan biasa ia kirimkan hampir setiap sore selama dua tahun belakangan sejak Tasya harus pindah mengikuti mutasi pekerjaan ayahnya ke pesisir Pangandaran.</p>
            <p>Namun, tepat di detik itu, gerakan jempolnya membeku di udara.</p>
            <p>Sakra membaca ulang pesan sederhana tersebut. Sekali. Dua kali. Tiga kali berturut-turut. Setiap kata, setiap karakter huruf, hingga emotikon wajah menangis kecil di ujung gelembung chat itu mendadak tampak memiliki bobot yang berbeda dari biasanya. Mata Sakra terkunci pada baris terakhir: <em>Udah makan belum?</em></p>
            <p>Ia telah membaca kalimat pertanyaan itu ratusan, bahkan ribuan kali selama kurang lebih 730 hari belakangan. Kalimat yang sama, dari orang yang sama, dengan pola ketikan yang tidak pernah berubah. Namun siang ini, di bawah terik matahari SMAN 90 Bandung, kalimat itu tidak lagi meluncur masuk ke dalam otaknya sebagai sapaan basa-basi dari seorang kawan lama.</p>
            <p>Ada denyut aneh yang mendadak melompat dari ulu hatinya, menjalar cepat menerobos rongga dada, lalu menyumbat tenggorokannya rapat-rapat. Napas Sakra tertahan seketika. Genggamannya pada bodi ponsel mengencang hingga ujung buku-buku jarinya memutih.</p>
            <p>Sakra perlahan memundurkan langkahnya, bersandar sepenuhnya pada tiang kayu gazebo yang kokoh. Pandangannya terlempar jauh, menembus kerapatan dahan pohon angsana, menatap langit siang Kota Bandung yang biru jernih tanpa sehelai awan pun.</p>
            <p>Dua tahun. Selama lebih dari tujuh ratus tiga puluh hari, ia dan Tasya telah hidup berdampingan di dalam sebuah kotak transparan yang mereka bangun sendiri: <em>sahabat dekat</em>. Ketika dua tahun lalu keluarga Tasya harus boyongan meninggalkan Bandung menuju Pangandaran—sebuah wilayah pesisir dan pegunungan kapur yang terbentang sejauh kurang lebih 179 kilometer dari ibu kota provinsi—Sakra sempat memperkirakan secara analitis bahwa jarak geografis itu perlahan-lahan akan membuat hubungan mereka merenggang secara alami.</p>
            <p>Saat itu, Sakra mengira komunikasi mereka akan memudar seiring berjalannya waktu. Ia berasumsi Tasya akan menemukan lingkungan pergaulan baru di SMAN 81 Pangandaran, bergabung dengan anak-anak pantai setempat, menemukan teman sebaya yang bisa menemaninya nongkrong sepulang sekolah, dan perlahan-lahan melupakan obrolan malam mereka di Bandung. Begitu pula sebaliknya; Sakra menduga dirinya akan kembali tenggelam seutuhnya dalam dunia pemrograman, tugas sekolah, dan kegiatan ekstrakurikulernya tanpa terbebani jarak.</p>
            <p>Namun, kalkulasi logisnya saat itu meleset jauh seratus delapan puluh derajat.</p>
            <p>Jarak fisik sejauh 179 kilometer nyatanya tak pernah sanggup meretas ikatan yang telah mereka rajut. Layar kaca berukuran enam inci justru bertransformasi menjadi jembatan permanen yang menghubungkan dua dunia yang berbeda setiap detik. Di ujung sana, Tasya dengan dinamika kehidupannya yang sibuk sebagai pengurus inti OSIS di SMAN 81 Pangandaran—sebuah sekolah unggulan di wilayah selatan yang kerap disibukkan dengan persiapan acara daerah, rapat pleno, perdebatan alot dengan pembina kesiswaan, hingga angin laut yang kadang menyelip di sela jendela ruang sekretariat. Sementara Sakra bertahan di Bandung dengan rutinitasnya sebagai siswa SMAN 90, pengurus MDC Pramuka yang bergelut dengan arsip digital, tugas-tugas eksak yang menumpuk, serta malam-malam panjang di depan monitor laptop menatap barisan skrip server.</p>
            <p>179 kilometer. Jika ditarik garis lurus di atas peta digital, angka itu merepresentasikan rentetan jalan raya berkelok-kelok yang membelah nagrek, turunan curam kawasan gentong, jembatan-jembatan tua, deretan tiang listrik tanpa putus, bukit-bukit kapur di selatan Jawa Barat, serta waktu tempuh perjalanan bus antar-wilayah yang memakan waktu empat hingga lima jam lamanya. Jarak yang membentang nyata, keras, dan tak terbantahkan. Bagi dua anak SMA yang belum memiliki kendaraan pribadi berkapasitas jauh atau kebebasan penuh untuk melintasi batas kabupaten kapan saja, 179 kilometer adalah benteng tak terlihat yang sangat kokoh.</p>
            <p>Namun selama dua tahun terakhir, benteng 179 kilometer itu seolah-olah runtuh tanpa daya di hadapan dering panggilan telepon malam hari, tawa renyah Tasya yang mengalir jernih dari speaker ponsel, atau rekaman suara acak berisi keluhan hari-hari sekolah yang sering kali baru berhenti ketika salah satu dari mereka tertidur lelah dengan ponsel masih menempel di dekat bantal.</p>
            <p>Akan tetapi, siang ini, tepat di hari pertama babak baru kehidupan SMA mereka, struktur dua tahun yang terasa begitu stabil itu mendadak bergoyang hebat dari dalam diri Sakra sendiri.</p>
            <p>Bukan karena pesan Tasya berbeda dari biasanya. Tidak sama sekali. Polanya persis sama. Yang berubah total adalah mekanisme pertahanan batin Sakra terhadap keberadaan pesan tersebut.</p>
            <p>Sakra menunduk kembali, menatap nama Tasya yang terpampang di layar. Dua kali ia salah memencet tombol <em>backspace</em> saat mencoba merangkai kata balasan awal—sebuah kecerobohan mekanis yang tak pernah dilakukan oleh seorang anak IT yang terbiasa mengetik cepat tanpa melihat kibor.</p>
            <p>Senyum tipis yang kini terukir di sudut bibirnya bukan lagi senyum seorang kawan lama yang merasa lega karena sahabat jauhnya memberi kabar. Senyum itu membawa getaran ketakutan kecil yang asing, rasa kagum yang mendadak meluap tanpa bisa dibendung, dan sebuah keinginan egois yang sebelumnya tak pernah ia izinkan hadir: keinginan untuk berada di samping gadis itu secara fisik. Bukan lagi sekadar sebagai sahabat yang mendengarkan keluh kesah dari balik layar, melainkan sebagai seorang pria yang memiliki hak penuh untuk menggenggam jemarinya di dunia nyata.</p>
            <p>Garis batas persahabatan itu telah terlampaui. Sakra melompati garis itu sendirian, tanpa suara, tanpa aba-aba, di sebuah siang yang terik di tepi lapangan sekolahnya.</p>
            <blockquote><em>“Kau terlalu indah, sehingga bulan kehilangan terangnya di balik bayang-bayangmu.”</em></blockquote>
            <p>Sebuah baris kalimat puitis yang tak sengaja pernah ia baca di sebuah linimasa sastra beberapa waktu lalu mendadak menggema kuat di dalam kepalanya. Dulu, ketika pertama kali membaca kalimat itu, Sakra hanya mencibir dalam hati. Sebagai remaja yang terbiasa berpikir dengan skema analitis, struktur data, dan hitungan pasti, ia selalu menganggap kalimat-kalimat bersayap seperti itu terlalu berlebihan dan tidak logis.</p>
            <p>Namun detik ini, saat bayangan wajah Tasya mendadak berputar di kepalanya—bagaimana gadis itu merapikan helai rambutnya yang tertiup angin pantai saat melakukan panggilan video, atau bagaimana mata Tasya berbinar penuh semangat setiap kali menceritakan keberhasilan program kerja OSIS-nya—kalimat puitis itu mendadak menemukan bentuk nyatanya.</p>
            <p>Tasya memang mempesona dengan seluruh kehadirannya. Mempesona dengan ketegasannya memimpin rapat di sekolahnya yang jauh di selatan, mempesona dengan nada bicaranya yang tak pernah kehabisan energi, dan mempesona dengan perhatian-perhatian kecil yang ia kirimkan secara alami, tanpa pernah sedikit pun menyadari betapa hal sederhana itu sanggup mengacak-acak ketenangan logika Sakra di Bandung.</p>
            <p>Sakra menarik napas dalam-dalam, menghembuskannya perlahan melalui mulut untuk meredakan debar dadanya yang berlari terlalu kencang. Ibu jarinya kembali menari di atas papan ketik virtual, menyeleksi setiap kata dengan ketelitian ekstra agar tidak kelihatan aneh.</p>
            <blockquote>
                <strong>Sakra:</strong> <em>“Biasa, baru beres ngerapihin berkas MDC Pramuka. Kesiswaan SMAN 81 emang terkenal paling rewel se-kabupaten wkwk. Nanti jangan lupa beli es teh manis atau kelapa muda di kantin luar biar pusingnya hilang. Ini gue juga mau siap-siap makan siang.”</em>
            </blockquote>
            <p>Tombol kirim ditekan. Tanda centang ganda berubah warna, menandakan paket data telah sukses dikirim ke server tujuan. Sakra menghembuskan napas panjang, menatap layar yang kini meredup dengan perasaan lega bercampur cemas yang absurd.</p>
            <p>"Sakra! Oi, Sakra! Jangan bilang lu dari tadi patung-patungan lagi di gazebo!"</p>
            <p>Sebuah teriakan lantang yang dibarengi suara derap sepatu karet menyentak ketenangan di sekitar area sanggar. Sakra tersentak kaget, hampir saja menjatuhkan ponselnya ke atas tanah sebelum dengan refleks cepat ia mengunci layar dan menyusupkannya ke dalam saku celana abu-abunya.</p>
            <p>Ia menoleh ke sumber suara. Indra berjalan melintasi lapangan dengan kaus olahraga oranye SMAN 90 yang basah kuyup oleh keringat setelah jam olahraga tambahan, mengibaskan handuk kecil ke leher jenjangnya. Di belakang Indra, Habib melangkah santai sambil memutar-mutar gantungan kunci motor di jari telunjuknya. Dua kawan sebayanya di SMAN 90 Bandung itu langsung menghampiri area gazebo dengan langkah lebar.</p>
            <p>Indra merosot menyandar ke tiang gazebo, mengatur napasnya yang masih memburu. "Lu dari tadi mandangin HP kayak dukun lagi baca mantra, Kra. Itu berkas mau dibawa ke galeri seni apa mau dipajang buat pameran agustusan?"</p>
            <p>Habib ikut menimpali sambil menyunggingkan senyum usil, matanya melirik saku celana Sakra yang agak mengembung oleh ponsel. "Muka lu pucat tapi senyum-senyum sendiri, Kra. Jangan bilang lu lagi chat-an sama anak Pangandaran?"</p>
            <p>Sakra langsung mematung sekian detik mendengar tebakan Habib yang terlalu tepat sasaran, meski ekspresinya lekas ia netralkan dengan dingin. "Ngaco lu, Bib. Gua lagi ngecek data biodata anggota baru MDC. Ada ejaan nama kelas sepuluh yang salah, makanya pusing sendiri."</p>
            <p>Tepat saat ia mencoba mengalihkan pembicaraan, layar ponsel Sakra di dalam saku kembali bergetar pelan. Bukan dari Tasya, melainkan sebuah pesan masuk dari aplikasi WhatsApp. Sakra melirik sekilas ke layar saat benda itu menyala di dalam saku.</p>
            <blockquote>
                <strong>Trea:</strong> <em>“Sak, lu jadi ke BIP sore ini buat ngambil pesenan kaset game retro pesenan gua? Jangan ngaret ya, awas lo.”</em>
            </blockquote>
            <p>Sakra menghela napas pelan, merogoh ponselnya sebentar untuk membalas cepat: <em>“Iya jadi, bawel.”</em></p>
            <p>Trea adalah teman karib mereka bertiga sejak SMP—Sakra, Tasya, dan Trea—sebelum Tasya harus pindah mengikuti keluarganya ke Pangandaran. Meskipun sekarang Trea bersekolah di SMA yang berbeda di Bandung, hubungan mereka bertiga tetap terjalin sangat erat lewat grup obrolan dan pertemuan akhir pekan. Fakta itu membuat Trea menjadi satu-satunya orang di Bandung yang paling tahu persis bagaimana sejarah panjang kedekatan Sakra dan Tasya dari nol, sekaligus orang yang paling sering mendengarkan keluh kesah Sakra secara langsung.</p>
            <p>"Dari siapa tuh? Trea ya?" tebak Habib tiba-tiba, memergoki layar Sakra yang menyala sekilas menampilkan nama pengirim. "Tuh kan, si Trea nge-chat mulu. Emang anak itu kalau nggak ngetag lu sehari rasanya ada yang kurang dari hidupnya."</p>
            <p>"Bukan apa-apa, nanyain soal nitip barang," elak Sakra cepat-cepat mematikan layar ponselnya dan memasukkannya kembali ke saku.</p>
            <p>Indra tertawa terbahak-bahak sambil merangkai lelucon garing. "Udah ah, yuk cabut ke kantin. Gua laper banget mau nyari mi ayam mang Uha di belakang. Biarin MDC-nya istirahat dulu, otaknya udah ngebul itu."</p>
            <p>"Sebentar, gua harus beresin arsip ini dulu ke dalam sanggar," tolak Sakra sopan, menunjuk tumpukan kertas biodata di atas meja.</p>
            <p>"Udah, biarin sebagian ditaruh lemari dulu. Buruan!" ajak Habib menarik lengan seragam Sakra agar berdiri.</p>
            <p>Sakra akhirnya menyerah. Ia mengunci pintu kayu sanggar Pramuka SMAN 90 Bandung, memasukkan anak kuncinya ke dalam saku, lalu berjalan beriringan bersama Indra dan Habib menyusuri koridor sekolah menuju kantin belakang. Di bawah pendar cahaya matahari siang yang menyengat, Indra dan Habib asyik memperdebatkan rencana pertandingan persahabatan futsal minggu depan, sementara Sakra menyentuh permukaan ponselnya di saku—mengingat pesan Trea, sekaligus membayangkan jarak 179 kilometer yang membentang menuju SMAN 81 Pangandaran.</p>
            <p>Hari pertama dari perjalanan baru ini telah resmi dimulai di lingkungan SMAN 90 Bandung. Sebuah kisah tentang rasa suka yang diam-diam ia simpan, menantang bentangan jarak yang memisahkan Bandung dan Pangandaran, yang siap mengarungi setiap detik dari babak paling menentukan dalam lembaran hidupnya.</p>
        `
    },
    { 
        title: "Bab 2: Hari ke-10 — Curhatan Malam dan Klien Sinting", 
        content: `
            <p>Sepuluh hari telah berlalu sejak garis batas itu bergeser secara diam-diam di gazebo SMAN 90 Bandung. Sepuluh hari yang bagi orang lain mungkin terasa seperti rentang waktu biasa di kalender akademik, namun bagi Sakra, setiap detiknya berjalan dengan intensitas yang berlipat ganda. Perasaan suka yang ia deklarasikan sendiri di dalam dadanya kini bukan lagi sekadar getaran sesaat, melainkan sebuah roda penggerak utama yang mengendalikan seluruh ritme dan fokus harinya.</p>
            <p>Setiap pagi saat terbangun di kamarnya yang beraroma dengung kipas <em>cooling pad</em> laptop, nama Tasya adalah hal pertama yang melintas di pikirannya. Dan setiap malam, sebelum ia benar-benar memejamkan mata di bawah remang cahaya lampu kamar, riwayat obrolan hijau di ponselnya adalah hal terakhir yang ia tatap.</p>
            <p>Namun, dunia Sakra tidak hanya berputar di sekitar bayang-bayang SMAN 81 Pangandaran. Di usianya yang baru menginjak belasan tahun, Sakra memikul realita lain yang jauh dari kata romantis: uang saku dari orang tuanya pas-pasan, sementara kebutuhan digitalnya—mulai dari sewa <em>Virtual Private Server</em> (VPS) Ubuntu, langganan internet tanpa batas, hingga tabungan untuk rencana jangka panjangnya—membutuhkan biaya yang tidak sedikit.</p>
            <p>Di sinilah sisi lain Sakra hidup. Di balik seragam putih abunya yang rapi, di balik jabatannya sebagai Ketua MDC Pramuka, Sakra adalah seorang <em>scripter</em> dan <strong>penjoki game profesional</strong>.</p>
            <p>Malam itu, jarum jam di sudut kanan bawah layar monitornya menunjuk pukul 22.15 WIB. Kamar berukuran tiga kali tiga meter itu gelap, hanya diterangi oleh pendar cahaya putih kebiruan dari layar monitor empat belas inci dan lampu LED strip di belakang meja belajar. Di atas meja, dua unit ponsel berderet berdampingan; satu ponsel khusus untuk memantau terminal <em>emulator</em> PC tempat skrip makro <em>auto-farming</em> game berjalan otomatis, dan satu lagi adalah ponsel pribadinya tempat obrolan Tasya berada.</p>
            <p>Tiba-tiba, ponsel pertama bergetar pendek. Notifikasi pesan WhatsApp masuk bertubi-tubi. Sakra, yang tadinya sedang fokus merapikan barisan kode skrip Python untuk menangani logika pergerakan karakter otomatis di <em>emulator</em>, menghela napas panjang dan menghentikan ketikannya di <em>keyboard</em> mekanikal.</p>
            <p>Ia meraih ponsel tersebut dan membuka aplikasi pesan. Pesan itu datang dari seorang klien yang menggunakan nama kontak Bara. Tidak ada huruf kapital penuh yang kekanak-kanakan, namun kalimat-kalimatnya justru terasa jauh lebih menyebalkan dan manipulatif.</p>
            <blockquote>
                <strong>Bara (Klien):</strong> <em>“Bro, ini akun kok dari sore stuck di Mythic Honor gak naik-naik bintangnya? Jangan bilang lu tidur ya. Gw bayar mahal bukan buat lu tinggal diem gini.”</em><br><br>
                <strong>Bara:</strong> <em>“Kalau besok pagi gak sampe Immortal, gw block ya pembayarannya. Tanggung jawab lo kalau winrate akun gw hancur gara-gara lu asal main.”</em>
            </blockquote>
            <p>Sakra memejamkan matanya sejenak, menarik napas dalam-dalam untuk menahan gelombang jengkel yang merembes ke pelipisnya. Bara adalah tipikal klien yang tidak paham sistem <em>matchmaking</em> game seluler; mereka hanya ingin hasil instan tanpa peduli kondisi <em>pool hero</em> atau sistem penalti dari server game tersebut.</p>
            <p>Sakra mengetik balasan dengan kepala dingin, memilih kata-kata yang tetap sopan namun tegas secara data.</p>
            <blockquote>
                <strong>Sakra:</strong> <em>“Malam, Kak Bara. Sesuai log emulator, akun kakak sempat turun karena match sebelumnya lose streak akibat rekan satu tim yang afk. Skrip makro sedang melakukan penyesuaian matchmaking secara bertahap. Estimasi selesai tetap sesuai jadwal besok sore. Mohon kerjasamanya agar proses re-login tidak mengganggu sistem.”</em><br><br>
                <strong>Bara:</strong> <em>“Alah, alasan klasik joki amatan. Pokoknya gw gak mau tau, kalau besok pagi gak beres, uang muka setengahnya gw hangusin.”</em>
            </blockquote>
            <p>Sakra mendengus kasar, lalu melempar ponsel joki itu ke atas tumpukan buku catatan. Ia merebalkan punggungnya ke sandaran kursi, memijat batang hidungnya yang berdenyut nyeri. Menjadi remaja mandiri yang menghasilkan uang sendiri ternyata menuntut mental yang tahan banting. Ia harus menelan ludah mentah-mentah saat direndahkan oleh klien di internet, menghabiskan waktu istirahat sekolah untuk tidur di kelas, dan mengorbankan jam tidurnya demi menaikkan bintang game orang lain.</p>
            <p>Di tengah rasa penat yang menghimpit dada, pandangan Sakra beralih ke ponsel pribadinya yang tergeletak di samping tetikus. Layar ponsel itu mendadak menyala menampilkan notifikasi baru.</p>
            <p>Sebuah gelembung pesan masuk dari Pangandaran.</p>
            <blockquote>
                <strong>Tasya:</strong> <em>“Sak... lu masih melek gak? Duh, gabut banget gue sumpah. Di rumah lagi sepi, mama sama abang lagi keluar kota nengok kakek, gue sendirian mana lampu teras mati lagi serem wkwk 😭 Lu lagi ngapening ya?”</em>
            </blockquote>
            <p>Melihat pesan itu, Sakra tidak langsung tersenyum lebar. Ia terdiam selama beberapa detik, menatap layar dengan mata yang menyipit karena lelah, lalu menarik napas panjang secara perlahan—melepaskan sisa-sisa emosi negatif dari Bara secara bertahap. Baru setelah itu, sudut bibirnya tertarik ke atas, membentuk senyum tipis yang perlahan-lahan mengusir penat di wajahnya. Sakra menyambar ponsel pribadinya, jemarinya bergerak lincah merangkai balasan.</p>
            <blockquote>
                <strong>Sakra:</strong> <em>“Gak sibuk kok, baru aja santai. Lah, lu sendirian di rumah? Makanya jangan suka nonton film horor mulu kalau penakut wkwk. Lampu teras mati tinggal dibenerin saklarnya.”</em><br><br>
                <strong>Tasya:</strong> <em>“Ih mana berani gue keluar malam-malam begini! Gelap tahu di luar. Sini temenin gue telponan dong, Sak, sebentar aja biar gak sunyi-sunyi banget rumahnya.”</em>
            </blockquote>
            <p>Tanpa berpikir dua kali, Sakra menekan ikon telepon di pojok kanan atas aplikasi obrolan mereka. Tidak butuh waktu tiga detik hingga sambungan itu terhubung. Suara napas Tasya yang agak tergesa-gesa langsung terdengar dari <em>speaker</em> ponsel, disusul suara televisi yang dikecilkan volumenya di ujung sana.</p>
            <p>"Halo... Sakra?" suara Tasya terdengar jelas, ada nada lega yang terselip di balik sapaan itu.</p>
            <p>"Iya, ini gua. Lu beneran sendirian di rumah seluas itu?" tanya Sakra, suaranya berubah jauh lebih lembut dibanding saat ia menghadapi Bara beberapa menit lalu. "Udah kunci semua pintu belum? Jendela kamar jangan lupa ditutup rapat."</p>
            <p>"Udah dikunci semua, bawel! Gue bukan anak kecil kali," protes Tasya di ujung sana, meski tawanya yang renyah menyusul kemudian. "Tadi gue lagi ngerjain tugas sejarah, tapi mendadak merinding sendiri pas denger suara angin di luar. Untung lu langsung angkat telpon."</p>
            <p>Sakra menyandarkan kepalanya ke kursi, mendengarkan setiap detail suara Tasya. Di kota seberang sana, di sebuah rumah di Pangandaran, gadis itu mungkin sedang meringkuk di atas sofa ruang tamu sambil memeluk guling. Jarak 179 kilometer mendadak terasa lenyap begitu frekuensi suara mereka bertemu di udara.</p>
            <p>"Makanya, jangan sok berani tinggal sendiri kalau mental masih ciut," ledek Sakra ringan. "Nih, dengerin suara gua biar gak sepi. Anggap aja gua lagi duduk di sofa sebelah lu."</p>
            <p>"Dih, PD banget," cibir Tasya, namun nadanya terdengar sangat menikmati kehadiran Sakra lewat sambungan suara itu. "Eh, Sak... lu tahu nggak? Hari ini di sekolah gue tuh rusuh banget. Si Rian, ketua OSIS itu lho, ngide bikin program Jumat bersih pantai. Bayangin aja, anak-anak OSIS disuruh manggung mulu mungutin sampah plastik di pinggir pantai pas panas-panas terik. Sumpah ya, muka gue langsung gosong sebelah!"</p>
            <p>Mendengar nama <em>Rian</em> disebut, ada sedikit sengatan kecil yang menusuk dada Sakra. Ia tahu persis siapa Rian—anak laki-laki satu sekolah di SMAN 81 Pangandaran yang sering muncul di cerita Tasya, seseorang yang bisa berdiri di samping Tasya secara fisik setiap hari, membantu mengangkat kardus proposal, atau berjalan bersama sepulang rapat OSIS.</p>
            <p>Namun, alih-alih terbakar cemburu buta, Sakra memilih mengendalikan logikanya. Ia menyimak setiap keluhan Tasya tentang Rian dan program pantai itu dengan sabar, menanggapi setiap lelucon Tasya, dan melemparkan candaan-candaan kecil yang membuat gadis itu tertawa terbahak-bahak di ujung sana.</p>
            <p>"Makanya jadi anak OSIS jangan nurut-nurut banget kalau ket가의 ngelunjak," komentar Sakra di sela tawanya. "Bilang tuh ke si Rian, MDC SMAN 90 Bandung siap ngirim skrip error ke laptop OSIS Pangandaran kalau kerjaannya nyiksa anggota."</p>
            <p>"Hahaha, gila ya lu! Komputer sekolah orang dizolimi!" protes Tasya diiringi tawa renyah yang membuat hati Sakra menghangat sempurna.</p>
            <p>Obrolan itu mengalir begitu saja, melompati berbagai topik tanpa arah yang jelas—dari mulai membahas guru sejarah mereka yang suka ketiduran di kelas, gosip artis nasional, hingga rencana liburan tahun depan. Sakra melupakan sejenak tentang Bara si klien joki yang menyebalkan, melupakan tumpukan kodingan server yang belum selesai, dan melupakan lelah fisiknya. Bagi Sakra, Tasya adalah tempat pemulihan terbaik. Suara gadis itu adalah penawar racun paling mujarab setelah seharian ia bergulat dengan kerasnya dunia nyata di Bandung.</p>
            <p>Di sela-sela obrolan mereka, suara ketukan pintu kamar Sakra tiba-tiba terdengar pelan.</p>
            <p><em>Tok... Tok... Tok...</em></p>
            <p>Sakra sedikit terlonjak. Ia melirik jam dinding kamarnya yang sudah menunjuk pukul 23.00 WIB. Pintu kamarnya berderit pelan saat didorong dari luar, memperlihatkan siluet Ibunya yang berdiri di ambang pintu sambil membawa segelas air putih hangat di atas nampan kecil.</p>
            <p>Ibu Sakra menatap anaknya yang masih mengenakan kaus rumahan dengan mata menyala di depan layar monitor ganda. Ibunya menghela napas panjang, mengisyaratkan lewat gestur tangan agar Sakra mengecilkan volume teleponnya sebentar.</p>
            <p>Sakra segera menutup <em>mic</em> ponselnya dengan telunjuk, lalu menoleh ke arah pintu. "Iya, Ma? Belum tidur?"</p>
            <p>Ibu melangkah masuk mendekati meja belajar, meletakkan segelas air hangat itu tepat di sebelah tetikus. Wanita paruh baya itu menatap lingkar hitam di bawah mata Sakra dengan tatapan penuh cemas dan teguran lembut.</p>
            <p>"Kamu ini mau jadi apa begadang terus tiap malam, Sakra?" bisik Ibu pelan namun tegas, tidak ingin suara ibunya terdengar oleh orang di ujung telepon. "Mama lihat dari kemarin-kemarin kamu di meja terus sampai jam dua pagi. Tugas sekolah jangan ditelantarkan demi ngurusin komputer atau game terus. Kesehatan kamu itu dijaga."</p>
            <p>"Iya, Ma, ini udah mau beres kok. Tinggal dikit lagi," jawab Sakra, berusaha tersenyum meyakinkan meski suaranya terdengar serak.</p>
            <p>Ibu mengelus puncak kepala Sakra pelan—sebuah gestur penuh kasih yang langsung membuat dada Sakra berdesir hangat. "Jangan terlalu diforsir. Uang memang penting, tapi badan kamu kalau sakit yang repot diri sendiri. MDC-MDCan itu nggak bakal nolong kalau kamu tumbang. Cepat tidur, ya."</p>
            <p>"Iya, Ma. Makasih air hangatnya," balas Sakra patuh.</p>
            <p>Ibu mengnodongkan kepala, lalu berbalik dan keluar kamar, menutup pintu rapat-rapat meninggalkan Sakra seorang diri lagi di ruangan yang remang.</p>
            <p>Sakra membuka kembali <em>mic</em> ponselnya. "Sya... masih di situ kan?"</p>
            <p>"Masih, kok! Gue denger tadi suara mama lu," jawab Tasya dengan nodal suara yang agak melembut. Nada suaranya mendadak berubah jadi penuh perhatian. "Tuh kan, mama lu aja negor lu gara-gara keseringan begadang. Lu beneran capek banget ya, Sak? Kalau lu ngantuk, tutup aja telponnya. Istirahat sana, kasihan mama lu merhatiin kesehatan lu."</p>
            <p>Mendengar perhatian tulus yang meluncur dari bibir Tasya, ada rasa haru yang membuncah di dalam dada Sakra. Perhatian itu terasa begitu natural. Tasya tidak pernah menuntut Sakra untuk menjadi sempurna, namun gadis itu selalu tahu kapan Sakra harus berhenti dan merawat dirinya sendiri.</p>
            <p>"Gak apa-apa, gua masih pengen ngobrol sama lu," ucap Sakra jujur, nada suaranya berubah manja tanpa ia sadari. "Gak rela nutup telponnya kalau sunyi begini."</p>
            <p>"Yaudah... kalau gitu kita tetep telponan gini, tapi lu sambil baringan di kasur ya? Pakai <em>earphone</em> biar tangan lu gak pegel megangin hp terus," saran Tasya di ujung sana, memberikan titah kecil yang langsung dituruti oleh Sakra tanpa bantahan.</p>
            <p>Sakra mengambil <em>earphone</em> kabelnya, mencolokkannya ke ponsel, lalu berjalan pelan meninggalkan kursi kerjanya dan merebahkan diri di atas kasur empuknya yang beraroma cucian bersih. Ia membetulkan posisi bantalnya, menatap langit-langit kamar yang gelap gulita sementara suara napas Tasya terdengar jernih langsung di kedua telinganya.</p>
            <p>"Udah dibaringan nih," lapor Sakra dengan suara pelan.</p>
            <p>"Bagus. Sekarang merem," perintah Tasya lembut.</p>
            <p>"Kalau gua merem, nanti lu malah tidur duluan."</p>
            <p>"Dih, emang kenapa kalau gue tidur duluan? Biarin biar lu juga ikutan tidur, bawel!" protes Tasya disusul tawa kecilnya yang renyah.</p>
            <p>Malam itu, di Hari ke-10, jurang pemisah berupa jarak 179 kilometer antara Bandung dan Pangandaran seolah-olah diratakan oleh kabel <em>earphone</em> dan suara lembut yang mengalir di telinga. Sakra menutup matanya, membiarkan kehangatan suara Tasya mengusir sisa-sisa amarah akibat ulah Bara si klien joki dan rasa lelah akibat tuntutan sekolah.</p>
            <p>Di sela-sela obrolan mereka yang makin lama makin melemah seiring datangnya rasa kantuk, Sakra menyadari satu hal yang pasti: ia sudah tenggelam terlalu dalam. Perasaan yang ia simpan rapat-rapat di balik topeng sahabat dekat itu bukan lagi sekadar api kecil yang bisa dipadamkan oleh logika; api itu sudah membesar, membakar seluruh keraguannya, dan menuntut untuk segera diwujudkan dalam sebuah tindakan nyata.</p>
            <p>Namun, sebelum hari itu tiba, Sakra masih harus melalui banyak malam panjang di balik layar monitornya—berjuang melawan lelah, mengumpulkan kembali kepingan asa, dan bersiap menyongsong badai-badai kecil yang siap menguji seberapa kuat ia mampu bertahan demi gadis di ujung selatan Jawa Barat sana.</p>
        `
    }
    // Nanti kalau mau nambahin Bab 3, tinggal kasih koma (,) di bawah sini lalu buat objek baru lagi!
];
