// File: data17.js
const novelData17 = [
    { 
        title: "Bab 19: Hari ke-150 — Antara Jakarta Hari Ini dan Serana", 
        content: `
            <p>Waktu terus bergulir, namun bagi Sakra, jarum jam di dinding kamarnya seolah berhenti berdetak tepat saat sambungan telepon dengan Tasya terputus beberapa hari yang lalu. Malam ini, kalender digital di sudut layar monitornya berpindah ke angka yang baru: <strong>Hari ke-150</strong>.</p>
            <p>Pukul 01.00 WIB. Udara Kota Bandung terasa jauh lebih dingin dari biasanya, menembus celah ventilasi dan membekukan ujung-ujung jari. Kamar berukuran tiga kali tiga meter itu gelap gulita, hanya diterangi oleh pendar biru redup dari layar monitor komputer yang dibiarkan menyala tanpa membuka program apa pun. Sakra duduk mematung di atas kursi kayunya, menatap layar kosong itu dengan pandangan nanar. Di kepalanya, kalimat pengakuan Tasya terus berputar bagaikan kaset rusak yang diputar berulang-ulang tanpa henti.</p>
            <p><em>“Lu ngasih 1000, sedangkan gue cuma bisa ngasih 10. Gue ngerasa jomplang banget, Sakra...”</em></p>
            <p>Kalimat itu menjelma menjadi hantu yang terus meneror kewarasannya. Sakra mengusap wajahnya dengan kasar. Rasa sesak di dadanya begitu menyiksa, seolah ada bongkahan batu besar yang tiba-tiba dijatuhkan tepat di atas paru-parunya. Ia tidak pernah membayangkan bahwa segala bentuk cinta, pengorbanan, darah, dan keringat yang ia peras demi menjaga hubungan ini justru menjadi belati yang mengiris mental kekasihnya sendiri secara perlahan.</p>
            <p>Untuk meredam suara-suara bising penyesalan di kepalanya, Sakra meraih <em>headset</em> hitam yang tergeletak di atas meja, memasangnya di kedua telinga, lalu memutar pemutar musik digitalnya. Jari-jarinya secara naluriah mencari daftar putar yang mewakili kehancurannya malam ini. Pilihan itu jatuh pada dua lagu dari band <em>emo</em> lokal favoritnya, <em>For Revenge</em>.</p>
            <p>Alunan melodi gitar yang melankolis dan dentuman drum yang sarat akan kepedihan dari lagu <strong>"Serana"</strong> langsung memenuhi rongga telinganya. Suara sang vokalis mengalun menyayat hati, melantunkan lirik tentang kehilangan, penyesalan, dan rasa sakit yang tak berkesudahan.</p>
            <p><em>“Di setiap masa yang telah kulewati... meluap bersama keluhku padamu...”</em></p>
            <p>Sakra memejamkan mata rapat-rapat. Lirik lagu itu seolah menampar wajahnya dengan kenyataan paling brutal. Ia teringat bagaimana ia menghabiskan malam-malam panjangnya mengetik kode untuk <em>Project_179</em>. Ia teringat bagaimana ia mengorbankan waktu tidurnya demi mencari uang lewat joki game hingga mimisan dan jatuh sakit. Ia mengira, semua itu adalah wujud pengorbanan paling heroik dari seorang laki-laki untuk membuktikan kesungguhan cintanya. Ia merasa menjadi pahlawan dalam cerita LDR mereka.</p>
            <p>Namun kini, pahlawan itu baru saja menyadari bahwa ia sendirilah yang telah membangun penjara rasa bersalah untuk sang putri.</p>
            <p>Lagu berikutnya berputar, <strong>"Jakarta Hari Ini"</strong>. Dentuman musik yang lebih keras seolah mengiringi hancurnya sisa-sisa ego Sakra. Lirik tentang melepaskan dan menerima kenyataan pahit menggemakan sebuah pencerahan yang menyakitkan. Cintanya terlalu besar, terlalu membludak, hingga menenggelamkan Tasya yang kapasitas perahunya tidak dirancang untuk menampung badai kasih sayang sebesar itu. <em>Over-giving</em>. Sebuah istilah psikologis yang dulu tidak pernah ia pedulikan, kini menjadi algojo yang mengeksekusi hubungan mereka.</p>
            <p>Tidak sanggup lagi menahan gemuruh di dadanya sendirian, Sakra membuka kunci layar ponselnya. Di jam satu pagi yang tidak masuk akal ini, ia tahu hanya ada satu orang yang bisa memberikannya sudut pandang yang jernih, objektif, dan tanpa filter.</p>
            <p>Sakra menekan nomor <strong>Trea</strong>.</p>
            <p>Nada sambung berbunyi cukup lama. Wajar saja, anak sekolah normal mana yang masih terjaga di jam segini. Namun, pada dering kelima, suara serak khas orang bangun tidur terdengar dari seberang.</p>
            <p>"Halo...?" sapa Trea dengan suara parau dan berat, terdengar sedikit kesal. "Sak? Lu gila ya nelpon jam satu pagi? Ada apa sih? Kalau lu cuma mau nanya tugas sekolah besok pagi gua..."</p>
            <p>"Tre..." potong Sakra cepat. Suaranya bergetar hebat, pecah, dan sarat akan keputusasaan. "Gua hancur, Tre. Semuanya hancur."</p>
            <p>Mendengar nada suara Sakra yang sangat rapuh dan putus asa—sebuah nada yang tidak pernah ia dengar bahkan saat Sakra ditipu oleh Bara tempo hari—kesadaran Trea langsung pulih seratus persen. Rasa kantuknya menguap seketika. Trea bangun dari posisi tidurnya dan duduk menyandar di kepala ranjang kamarnya.</p>
            <p>"Sak? Lu kenapa? Tarik napas pelan-pelan dulu," instruksi Trea, nada suaranya berubah menjadi sangat serius dan protektif. "Ada apa sama lu? Ini soal Tasya?"</p>
            <p>Di dalam kamarnya yang remang, Sakra menundukkan kepala dalam-dalam. "Dia nangis, Tre... dia bilang dia ngerasa jomplang. Dia bilang <em>effort</em> gua selama ini cuma bikin dia ngerasa jadi pacar yang gak becus karena dia gak bisa bales apa-apa yang setara. Dia... dia hancur karena gua, Tre."</p>
            <p>Di ujung telepon, Trea terdiam cukup lama. Hanya terdengar suara helaan napas panjang yang mengalir berat dari hidung gadis berjaket <em>denim</em> tersebut. Trea sama sekali tidak terkejut dengan kabar ini. Sebagai sahabat karib yang menampung seluruh curhatan Tasya di Pangandaran dan mengamati langsung gerak-gerik Sakra di Bandung, Trea sudah memprediksi bahwa ledakan ini hanya masalah waktu.</p>
            <p>"Gua udah tahu hari ini bakal datang, Sak," ucap Trea akhirnya, suaranya terdengar sangat tenang, namun menghunjam tepat di titik kesadaran Sakra.</p>
            <p>"Lu... lu udah tahu kalau dia selama ini kesiksa?" tanya Sakra terbata-bata, rasa bersalah semakin meremas jantungnya.</p>
            <p>"Gua udah pernah peringatin lu, kan? Pas kita ketemu di Bandung waktu Lebaran," balas Trea tegas tanpa bermaksud menghakimi. "Gua bilang, kurangi ngasih ini-itu ke Tasya secara berlebihan. Tasya itu beda sama cewek lain yang mungkin bakal seneng-seneng aja kalau dimanjain habis-habisan. Tasya itu punya harga diri, punya empati yang kelewat tinggi, dan dia gampang banget ngerasa punya <em>utang budi</em>."</p>
            <p>Sakra terdiam, meresapi setiap pukulan realita dari kata-kata Trea.</p>
            <p>"Lu harus paham psikologis cewek kayak Tasya, Sak," lanjut Trea membedah anatomi kehancuran sahabatnya. "Saat lu bikin <em>Project_179</em> yang luar biasa megah itu, lu ngerasa lu udah ngasih dunia lu buat dia. Tapi di sisi Tasya? Dia ngeliat itu sebagai standar yang terlalu tinggi buat dia capai. Pas lu sakit-sakitan, pingsan, banting tulang di Bandung, lu mikir lu berkorban demi dia. Tapi di sisi Tasya? Dia ngerasa dia adalah penyebab lu menderita, dan dia benci dirinya sendiri karena gak bisa berbuat apa-apa selain ngeliatin lu dari jauh lewat layar HP."</p>
            <p>"Gua gak pernah niat bikin dia ngerasa kayak gitu, Tre... sumpah demi apa pun, gua gak pernah nuntut balesan sepeser pun dari dia," rintih Sakra putus asa, suaranya nyaris hilang ditelan lagu <em>Serana</em> yang masih berputar samar dari <em>headset</em> di lehernya.</p>
            <p>"Gua tahu, Sakra. Sumpah, gua tahu niat lu tulus," jawab Trea melembut, menyadari bahwa pemuda di seberang sana juga sama hancurnya. "Tapi di dalam sebuah hubungan, niat baik aja gak cukup kalau lu gak ngukur kapasitas pasangan lu. Cinta yang lu kasih itu terlalu besar, terlalu berat, sampai-sampai Tasya tertimpa dan gak bisa napas. Dia hancur bukan karena lu jahat, tapi dia hancur oleh rasa bersalahnya sendiri akibat <em>over-giving</em> lu yang gak ngasih dia ruang buat berkontribusi secara seimbang."</p>
            <p>Kata-kata Trea menjadi palu godam terakhir yang menghancurkan sisa-sisa ego Sakra. Semuanya menjadi sangat jelas sekarang. Jurang ketimpangan itu murni tercipta dari tangannya sendiri. Jarak 179 kilometer yang selama ini ia salahkan, ternyata bukanlah musuh utamanya. Musuh terbesar yang merusak hubungan mereka adalah ketidakmampuannya membaca luka yang ia torehkan atas nama cinta.</p>
            <p>"Terus sekarang gua harus apa, Tre?" bisik Sakra, nyaris seperti isakan anak kecil yang tersesat di tengah hutan. "Gua sayang banget sama dia. Gua gak mau kehilangan dia."</p>
            <p>Trea menghela napas panjang, menatap langit-langit kamarnya dengan perasaan campur aduk. "Gua gak bisa ngasih lu jawaban instan, Sak. Ini bukan error di kode <em>script</em> lu yang bisa di-fix pakai <em>debug</em> dalam semalam. Ini soal perasaan manusia yang udah terlanjur babak belur. Untuk sekarang, kasih dia ruang. Mundur selangkah. Jangan paksa dia buat nerima apa-apa lagi dari lu, dan biarin dia bernapas lega tanpa harus ngerasa berutang budi."</p>
            <p>Panggilan telepon malam itu berakhir tepat pukul dua pagi.</p>
            <p>Sakra meletakkan ponselnya di atas meja dengan tangan yang gemetar. Ia melepas <em>headset</em> dari telinganya, membiarkan alunan lagu <em>Jakarta Hari Ini</em> memudar seiring dengan keheningan malam yang kembali menelan kamarnya.</p>
            <p>Di Hari ke-150 ini, di bawah bayang-bayang kegagalan yang menyakitkan, Sakra harus menelan pil paling pahit dalam proses pendewasaan remajanya. Bahwa terkadang, mencintai seseorang dengan teramat sangat justru berarti bersedia untuk tidak memaksakan kehadiran kita, dan bahwa cinta yang sejati tidak akan pernah menuntut seseorang untuk kehilangan harga dirinya hanya demi menyamakan sebuah timbangan yang tak kasat mata.</p>
        `
    }
];
