// File: data2.js
const novelData2 = [
    { 
        title: "Bab 3: Hari ke-28 — Menahan Diri di Tengah Hujan", 
        content: `
            <p>Dua puluh delapan hari. Kurang dari sebulan sejak garis batas itu bergeser secara diam-diam di gazebo SMAN 90 Bandung. Selama rentang waktu itu, ritme hidup Sakra terbagi menjadi dua dunia yang saling bertolak belakang: siang hari yang bising di lingkungan sekolah, dan malam hari yang sunyi di balik layar monitor tempat ia merajut asa lintas kabupaten bersama Tasya di SMAN 81 Pangandaran.</p>
            <p>Hari itu, langit Bandung menunjukkan tabiat buruknya sejak matahari bergeser ke barat. Pukul tiga sore, awan kumulonimbus berwarna kelabu pekat menggantung rendah di atas atap-atap gedung sekolah, menutupi sisa-sisa cahaya biru kemerahan. Udara mendadak terasa lembap, berbau tanah basah yang diangkat angin dari hamparan rumput lapangan.</p>
            <p>Di dalam sanggar Pramuka SMAN 90 Bandung, suasana tidak kalah runyam.</p>
            <p>Sakra sedang duduk bersila di dekat meja kayu panjang, memegang sebuah <em>flashdisk</em> hitam berukuran kecil di antara ibu jari dan telunjuknya. Di hadapannya, Dimas—anggota junior MDC yang dikenal sering ceroboh dan hobi menghindar dari tanggung jawab—berdiri sambil menggigit kuku, memasang wajah pucat pasi.</p>
            <p>"Maksud lo apa, Dim? <em>Flashdisk</em> data rekapitulasi inventaris ambalan dan arsip digital kelas sepuluh yang kemarin dititipin ke lo... sekarang ilang?" suara Sakra terdengar tenang, namun nadanya sedingin es. Tidak ada bentakan, tidak ada nada tinggi. Justru ketenangan itu yang membuat Dimas semakin ketakutan.</p>
            <p>"S-sumpah, Kak Sakra... kemarin pas pulang latihan, tak taruh di dalam saku tas ransel. Tapi tadi pas tak cari di rumah, tasnya kosong, kayaknya jatoh di sekitar sanggar atau kantin..." cicit Dimas gemetar, keringat dingin bercucuran di pelipisnya.</p>
            <p>Sakra menghela napas panjang. Ia menutup matanya sejenak, meredam gelombang emosi yang mendadak mendesak naik ke dadanya. Bagi seorang Ketua MDC yang sangat menjunjung tinggi keteraturan data, kehilangan <em>flashdisk</em> berisi <em>backup</em> arsip penting tanpa salinan <em>cloud</em> yang mutakhir adalah sebuah pukulan telak. Tengkorak kepalanya mendadak berdenyut nyeri. Masalah ini tidak boleh dibiarkan begitu saja; jika data itu tidak ditemukan, ia harus merelakan waktu semalaman untuk menyusun ulang seluruh lembar rekap dari nol sebelum laporan diserahkan ke pembina esok pagi.</p>
            <p>Sebelum Sakra sempat melontarkan teguran yang lebih telak, suara dentuman guntur membelah langit angkasa dengan garang.</p>
            <p><em>Bummmm!</em></p>
            <p>Detik berikutnya, langit Bandung benar-benar runtuh. Air hujan tumpah ruah dalam skala masif, menghantam atap seng sanggar Pramuka dengan suara gemuruh yang memekakkan telinga. Angin kencang bertiup liar, menerbangkan debu dan menepiskan air hujan hingga membasahi lantai teras sanggar. Bau petrikor yang tajam menyeruak, beradu dengan aroma lembap kayu tua ruangan tersebut.</p>
            <p>"Udah, urusan si Dimas lu pending dulu, Kra. Nih <em>flashdisk</em> bisa dicari lagi nanti, tapi kalau lu berdiri terus di situ muka lu bisa pucat pasi kayak mayat," sergah suara serak dari ambang pintu.</p>
            <p>Indra dan Habib muncul dari balik tirai air hujan, berlari kecil menerobos amukan badai dengan seragam Pramuka yang basah di bagian bahu. Habib membawa sebungkus kantong plastik putih berukuran sedang, sementara Indra langsung menutup pintu kayu sanggar rapat-rapat untuk menghalau cipratan air.</p>
            <p>"Gila, badai dadakan Bandung mah emang nggak ngotak!" cibir Indra sambil mengibas-ngibaskan ujung lengan bajunya yang basah. Ia melempar handuk kecil ke meja, lalu melirik tajam ke arah Dimas. "Lu masih di sini, Dim? Mau meluk tiang? Sana minggat dulu, biarin Ketua MDC kita lagi pusing mikirin data lu yang lenyap. Besok pagi lu harus sudah bawa kabar atau gua aduin ke Kak Nisa!"</p>
            <p>Tanpa buang waktu, Dimas langsung kabur meninggalkan sanggar, memanfaatkan kesempatan dalam kesempitan.</p>
            <p>Meski Dimas sudah pergi, rasa kesal di dada Sakra belum sepenuhnya menguap. Kepalanya masih berdenyut memikirkan konsekuensi dari hilangnya arsip tersebut. Namun, sebelum ia sempat membuka laptop untuk memeriksa salinan lama di direktori lokal, Habib melangkah mendekat dan membuka kantong plastik putih yang dibawanya.</p>
            <p>Habib mengeluarkan tiga mangkuk plastik berisi batagor hangat berkuah kacang kental yang mengepulkan uap putih. Bau gurih kacang tanah dan jeruk limau langsung memenuhi ruangan yang tadinya berbau lembap.</p>
            <p>"Nih, buat nyuci otak lu yang lagi pening gara-gara si Dimas ceroboh," kata Habib menyodorkan semangkuk batagor ke hadapan Sakra. "Makan dulu, Kra. Masalah data ilang emang bikin stres, tapi perut kosong bakal bikin lu makin gila."</p>
            <p>Sakra menatap mangkuk batagor itu sekilas, lalu mengusap wajahnya dengan kedua tangan. Ia sadar, memandangi meja kosong tidak akan mengembalikan <em>flashdisk</em> itu seketika. Dengan gerakan lesu, ia menarik mangkuk tersebut mendekat, meski pikirannya masih separuh melayang pada tumpukan tugas yang menanti esok hari.</p>
            <p>Di tengah badai sore itu, ponsel di dalam saku Sakra bergetar pelan.</p>
            <p>Sakra langsung merogoh sakunya. Layar menyala, menampilkan pesan dari Tasya yang dikirim dari Pangandaran.</p>
            <blockquote>
                <strong>Tasya:</strong> <em>“Sak... di Bandung hujan deras banget gak? Di sini anginnya kencang banget, sampai atap seng di sebelah sekolah bunyi. Sumpah serem, gue lagi sendirian di ruang OSIS nunggu jemputan mama. Lu lagi di mana? Kangen...”</em>
            </blockquote>
            <p>Membaca kata <em>kangen</em> di ujung pesan itu, pertahanan rasional Sakra mendadak mengalami guncangan. Transisi emosinya terjadi begitu cepat—dari seorang ketua organisasi yang ketat dan jengkel pada anak buahnya, seketika berubah menjadi remaja yang dihantam gelombang rindu luar biasa.</p>
            <p>Di dalam ruang sanggar yang beraroma basah, di tengah omelan kecil Indra dan Habib yang sedang melahap batagor, pikiran Sakra langsung meloncat menyeberang 179 kilometer menuju pesisir selatan Jawa Barat. Ia membayangkan Tasya di sana—duduk seorang diri di ruang OSIS SMAN 81 Pangandaran yang dingin, mendengarkan deru angin laut dan hujan badai yang menghantam jendela, tanpa ada siapa pun di sampingnya.</p>
            <p>Ada dorongan yang begitu kuat di dalam dada Sakra untuk membalas pesan itu dengan kalimat gegabah: <em>“Tunggu ya Sya, gue cabut sekarang naik bus ke Pangandaran buat meluk lu.”</em></p>
            <p>Sebuah keinginan impulsif yang lahir dari rasa cinta yang mulai mendominasi akal sehatnya. Sakra ingin melompati jarak 179 kilometer itu detik ini juga. Ia ingin berdiri di hadapan Tasya, membawakan jaket hangat, dan memastikan gadis itu tidak merasa sendirian di tengah cuaca buruk.</p>
            <p>Namun, realita langsung menamparnya telak.</p>
            <p>Jalanan Bandung menuju Pangandaran di tengah badai besar seperti ini adalah mimpi buruk. Jalur nagrek dan kawasan gentong terkenal rawan longsor saat curah hujan tinggi. Ongkos bus, waktu tempuh lima jam, serta kewajibannya sebagai siswa MDC yang esok harinya harus membereskan kekacauan data dari Dimas membuat angan-angan itu mendadak terasa begitu mustahil.</p>
            <p>Sakra terjebak di sini. Di Bandung. Di balik meja kayu sanggar yang basah.</p>
            <p>"Kra? Malah melamun. Batagornya keburu dingin tuh, kuahnya udah mulai meresap ke siomaynya," tegur Indra sambil menyumpit sepotong pangsit goreng ke dalam mulutnya.</p>
            <p>Sakra mengerjap perlahan, menarik napas dalam-dalam untuk menormalkan debar jantungnya. Ia menatap layar ponselnya, lalu mulai mengetik balasan dengan jempol yang sedikit gemetar karena menahan gejolak rindu yang teramat sangat.</p>
            <blockquote>
                <strong>Sakra:</strong> <em>“Iya, Sya, di Bandung juga lagi badai parah nih. Hati-hati di ruang OSIS, jangan keluar kalau belum dijemput mama. Kalau takut, telpon gue sekarang. Gue ada di sanggar nemenin lu lewat hp.”</em>
            </blockquote>
            <p>Tidak sampai lima detik setelah pesan itu terkirim, layar ponselnya berubah menjadi panggilan masuk dari Tasya.</p>
            <p>Sakra langsung menekan tombol hijau, mendekatkan ponsel ke telinganya di tengah suara hujan deras di luar dan suara batagor yang dikunyah Habib di dalam ruangan.</p>
            <p>"Halo, Sakra..." suara Tasya terdengar gemetar di ujung sana, bercampur dengan suara deru angin kencang yang menghantam kaca jendela SMAN 81 Pangandaran. "Gue merinding banget denger suara geledek di luar. Lampu koridor sekolah juga sempat kedip-kedip tadi."</p>
            <p>"Iya, Sya, denger nih suara hujan di Bandung juga gede banget," ucap Sakra lembut, sengaja mendekatkan mikrofon ponselnya ke arah jendela sanggar agar suara gemuruh hujan dan petir terdengar jelas di telinga Tasya. "Gue di sini, nemenin lu. Jangan takut ya."</p>
            <p>Di ujung seberang sana, Tasya menarik napas panjang, mencoba menenangkan diri. "Sak... lu tahu nggak? Tadi pas badai mulai datang, gue tiba-tiba pengen banget lu ada di sini. Rasanya capek banget harus ngelewatin cuaca jelek sendirian kayak gini."</p>
            <p>Kata-kata itu meluncur begitu jujur, menghujam langsung ke lubuk hati Sakra. Ada rasa sakit yang menyayat-nyayat dadanya—rasa sakit karena menyadari betapa kejamnya angka 179 kilometer yang memisahkan fisik mereka saat salah satu dari mereka sedang merasa rapuh.</p>
            <p>Sakra mengepalkan tangan kirinya erat-erat di atas pangkuannya. Giginya mengatup rapat, menahan beban emosional yang mendadak terasa begitu berat. Ia ingin sekali mengatakan bahwa ia akan melakukan apa saja untuk memperpendek jarak itu. Namun, ia juga sadar, ia hanyalah seorang remaja SMA biasa yang terikat oleh waktu, jarak, dan keterbatasan.</p>
            <p>"Sabar ya, Sya," bisik Sakra parau, suaranya nyaris tenggelam oleh suara hujan lebat di sanggar.</p>
            <p>Indra dan Habib yang duduk di sudut ruangan mendadak menghentikan kunyahan mereka. Mereka saling berpandangan sekilas, menangkap perubahan nada suara Sakra yang mendadak sangat serius, lembut, dan penuh beban. Indra mengisyaratkan pada Habib dengan gerakan mata agar tidak bersuara keras-keras, menghargai privasi sahabat mereka yang sedang bertarung dengan badai rindu lintas kabupaten.</p>
            <p>Malam itu, di Hari ke-28, di tengah badai hujan yang melumpuhkan Bandung dan Pangandaran, Sakra belajar arti paling pahit dari sebuah hubungan jarak jauh: terkadang, bentuk cinta yang paling besar bukanlah tentang seberapa sering kita bersama, melainkan tentang seberapa kuat kita harus <strong>menahan diri</strong> untuk tidak menerjang batas ketika semesta sedang tidak berpihak pada pertemuan. Dan esok hari, di balik sisa-sisa kelelahan itu, Sakra tahu ia masih harus menghadapi setumpuk data yang hilang di ruang MDC SMAN 90 Bandung.</p>
        `
    },
    { 
        title: "Bab 4: Hari ke-45 — Dua Layar, Dua Dunia", 
        content: `
            <p>Dua belas hari telah berlalu sejak badai sore itu mereda di Bandung. Pagi ini, udara SMAN 90 Bandung kembali diuji oleh terik matahari yang menyengat sejak pukul delapan pagi. Di dalam kelas XII IPA 2, suasana terasa kaku karena guru mata pelajaran Fisika, Pak Wahyu, sedang menuliskan rumus termodinamika yang panjang dan rumit di papan tulis. Suara kapur putih yang bergesekan dengan permukaan papan menciptakan suara <em>cit-cit</em> tajam yang menusuk telinga.</p>
            <p>Sakra duduk di bangku baris kedua dari depan, namun pikirannya berada di tempat yang sangat jauh dari rumus-rumus mesin kalor tersebut.</p>
            <p>Matanya menatap kosong ke arah buku catatan di hadapannya. Semalaman penuh, Sakra tidak tidur sedetik pun. Ia harus begadang sampai subuh untuk memulihkan seluruh data <em>backup</em> MDC yang hilang akibat <em>flashdisk</em> Dimas, sekaligus menyelesaikan target <em>rank</em> pesanan Bara si klien joki yang terus-menerus menagih <em>progress</em>. Akibat kurang tidur yang kronis dan beban fisik yang terforsir, kepalanya terasa berdenyut-denyut nyeri hebat.</p>
            <p><em>Cok...</em></p>
            <p>Sakra merasakan ada cairan hangat yang mengalir tiba-tiba dari lubang hidung kanannya.</p>
            <p>Ia mengerjap cepat, lalu meraba hidungnya dengan punggung tangan. Saat ia menarik tangannya kembali, noda darah segar berwarna merah pekat telah mengotori kulit jarinya. Sakra mendesah pelan. Mimisan. Ini adalah kali kedua minggu ini ia mengalami pendarahan hidung akibat kelelahan ekstrem.</p>
            <p>Tanpa menimbulkan suara gaduh yang bisa menarik perhatian Pak Wahyu, Sakra merogoh saku celananya, mengambil selembar tisu putih, lalu menyumpal hidungnya rapat-rapat. Ia menundukkan kepala, mencoba mengatur napasnya yang pendek.</p>
            <p>Di bangku sebelah kirinya, Indra melirik sekilas ke arah Sakra. Wajah Indra langsung mengernyit ngeri melihat tisu berdarah di hidung Sakra.</p>
            <p>"Walah, Kra... lu mimisan lagi?" bisik Indra cemas, menggeser sedikit kursinya. "Gila, muka lu pucat banget kayak zombi kurang darah. Lu beneran mau mati muda gara-gara ngurusin joki game sama data Pramuka?"</p>
            <p>"Gue gak apa-apa, Ndra. Kurang cairan doang," balas Sakra berbisik parau, suaranya serak dan nyaris tak terdengar di atas suara Pak Wahyu yang sedang menjelaskan siklus Carnot.</p>
            <p>"Gak apa-apa kepala lu peyang!" gerutu Indra kesal. "Tugas kelompok fisika kemarin aja lu gak kerjain bagian lu kan? Kalau bukan karena gue sama Habib yang nutupin kerjaan lu di depan Pak Wahyu, lu pasti udah diseret ke ruang BK."</p>
            <p>Sakra hanya bisa diam. Ia tahu Indra benar. Ia sudah mulai keteteran di sekolah. Nilai ulangannya mulai turun, dan beberapa kali ia ketahuan tidur di kelas oleh guru piket. Di balik keteraturan barisan kode skrip yang ia buat di kamar, kehidupan nyata Sakra di SMAN 90 Bandung sedang berada di ambang kehancuran perlahan-lahan.</p>
            <p>Namun, di saat yang hampir bersamaan, sejauh 179 kilometer ke arah tenggara, di koridor SMAN 81 Pangandaran, dunia berjalan dengan ritme yang sama sekali berbeda namun sama melelahkannya.</p>
            <p>Tasya sedang berdiri di depan ruang sekretariat OSIS, memegang setumpuk kardus berisi proposal kegiatan pentas seni yang baru saja dicetak. Angin laut yang membawa bau garam berembus kencang, menerbangkan helaian rambut Tasya yang diikat kuda. Di sampingnya, Rian—sang Ketua OSIS SMAN 81 yang berpostur tinggi tegap dengan jas almamater rapi—berjalan mendekat sambil membawa dua botol air mineral dingin.</p>
            <p>"Nih, minum dulu, Sya. Keliatan banget capeknya dari tadi pagi ngurusin revisi proposal," kata Rian ramah sambil menyodorkan sebotol air mineral kepada Tasya.</p>
            <p>Tasya menoleh, tersenyum sopan lalu menerima botol tersebut. "Makasih banyak ya, Rian. Duh, untung ada lu yang bantu angkatin kardus ini, kalau sendirian bisa encok pinggang gue."</p>
            <p>"Santai aja, emang udah tugas kita buat saling bantu di OSIS," canda Rian tertawa renyah.</p>
            <p>Bagi Tasya, kehadiran Rian di sekolah adalah sebuah bentuk pertolongan fisik yang nyata. Setiap kali ia kelelahan membawa tumpukan dokumen, kesulitan mengatur jadwal rapat, atau butuh bantuan mengangkat barang berat di lingkungan SMAN 81, Rian selalu ada di sampingnya tanpa harus diminta. Namun, di balik rasa terima kasihnya itu, terselip sebuah kontras yang makin hari makin menghujam batin Tasya.</p>
            <p>Rian membantunya secara nyata dan fisik di sini, di sekolah yang sama. Sementara Sakra... kekasihnya yang terpisah jarak 179 kilometer di Bandung, harus membanting tulang seorang diri, begadang melayani klien joki game, dan mengiriminya makanan lewat ojek <em>online</em> lintas kota dengan pengorbanan yang tak terlihat oleh mata.</p>
            <p>Saat Tasya membuka tas sekolahnya untuk mengambil ponsel, pandangannya tertumbuk pada sebuah struk kertas kecil dari pengiriman ojek <em>online</em> lintas kota yang terselip di dalam buku catatannya.</p>
            <p>Melihat struk itu, senyum di wajah Tasya perlahan memudar, digantikan oleh tarikan napas berat yang sarat akan rasa bersalah.</p>
            <p>Beberapa hari lalu, teman-teman OSIS-nya sempat bergosip di ruang sekretariat: <em>"Pacar lu tuh hebat banget ya, Sya, perhatian mulu dari Bandung. Tapi kalau lu di sini dibantuin mulu sama Rian secara langsung, sementara pacar lu berdarah-darah di sana, lama-lama keliatan jomplang banget."</em></p>
            <p>Kalimat-kalimat itu berputar-putar di kepala Tasya, memperparah rasa <em>insecure</em> yang menggerogoti hatinya. Tasya merasa dirinya adalah pacar yang buruk—menerima terlalu banyak pengorbanan dari Sakra, namun hanya bisa berpangku tangan dan mengandalkan bantuan fisik dari Rian di sekolah.</p>
            <p>Tasya membuka kunci layar ponselnya. Ada pesan baru dari Sakra yang dikirim setengah jam lalu:</p>
            <blockquote>
                <strong>Sakra:</strong> <em>“Lagi istirahat ya, Sya? Jangan lupa makan siang ya, jangan telat lambungnya.”</em>
            </blockquote>
            <p>Tasya menatap pesan itu lama sekali, dadanya terasa sesak oleh timbunan rasa bersalah yang teramat berat.</p>
            <p>Kembali ke kelas XII IPA 2 SMAN 90 Bandung, bel istirahat akhirnya berbunyi nyaring.</p>
            <p><em>Kringgggg!</em></p>
            <p>Pak Wahyu membereskan buku-bukunya dan meninggalkan kelas. Sontak, suasana kelas langsung pecah oleh suara kursi yang digeser dan gerutuan para siswa.</p>
            <p>Sakra melepas tisu dari hidungnya, memastikan pendarahan kecil itu sudah berhenti meski meninggalkan rasa pening yang berdenyut di pelipis. Ia meraih ponselnya dari saku, berniat membalas pesan Tasya. Namun sebelum sempat ia mengetik, layar ponselnya bergetar. Sebuah panggilan suara masuk dari Trea, sahabat perempuannya yang bersekolah di SMA lain di Bandung.</p>
            <p>Sakra menggeser tombol hijau dan mendekatkan ponsel ke telinganya.</p>
            <p>"Halo, Sakra? Lu di mana sekarang?" suara Trea langsung terdengar mendesak di ujung sana, tanpa basa-basi ucapan salam. Nada suara Trea terdengar gelisah.</p>
            <p>"Gue di kelas, baru beres pelajaran Fisika. Kenapa, Tre?" tanya Sakra bingung.</p>
            <p>"Lu mendingan cek <em>chat</em> dari Tasya sekarang deh, atau coba telpon dia," ujar Trea dengan nada serius. "Barusan gue gak sengaja ngobrol agak lama sama Tasya lewat telpon. Sumpah ya, Sak, anak itu lagi down banget. Dia cerita sambil nangis-nangis ke gue."</p>
            <p>Jantung Sakra mendadak berdegup kencang. Kantuk dan pening di kepalanya seketika menguap entah ke mana.</p>
            <p>"Nangis? Tasya kenapa, Tre? Ada masalah apa di Pangandaran?"</p>
            <p>"Bukannya ada masalah di sekolah, tapi dia mikirin <em>lu</em>, Sakra!" suara Trea meninggi di ujung sana, menyuarakan kekesalan sekaligus rasa khawatirnya sebagai sesama sahabat perempuan Tasya. "Tasya ngerasa bersalah banget karena dia ngerasa gak bisa ngimbangin semua pengorbanan, barang-barang, dan perhatian yang lu kasih ke dia. Dia bilang dia capek ngerasa jadi beban buat lu yang di Bandung kerja keras banting tulang sendirian."</p>
            <p>Penjelasan Trea menghantam dada Sakra seperti hantaman palu godam.</p>
            <p>Sakra terdiam kaku di bangkunya. Ponsel di tangannya terasa mendadak sangat berat. Ia mengira segala bentuk perhatian, kerja keras, dan pengorbanan malam-malam yang ia lakukan adalah bentuk cinta terbaik untuk menjaga Tasya. Namun ia tidak pernah menyangka, di seberang sana, di balik layar ponsel yang sama, niat baiknya justru menjadi sumber beban mental dan air mata bagi gadis yang paling ia cintai.</p>
            <p>Dua layar, dua dunia yang terpisah 179 kilometer. Di sinilah benturan nyata itu dimulai—ketika ketulusan yang diberikan tanpa takaran yang pas justru mulai meretakkan hal yang paling ingin mereka jaga.</p>
        `
    }
];
