// File: data7.js
const novelData7 = [
    { 
        title: "Bab 9: Hari ke-100 — Titik Terendah Sakra", 
        content: `
            <p>Lima hari telah berlalu sejak malam penuh air mata di mana badai bernama Bara merenggut seluruh hasil jerih payah Sakra. Lima hari yang berjalan bagaikan mimpi buruk yang tak kunjung berujung. Di dalam kalender digital kehidupan Sakra, hari itu tepat jatuh pada Hari ke-100—sebuah angka penanda yang ironis, di mana alih-alih merayakan ketahanan hubungan atau kemajuan proyek digitalnya, Sakra justru terperosok ke dalam titik nadir paling rendah dalam hidupnya.</p>
            <p>Kamar berukuran tiga kali tiga meter itu berubah menjadi ruang isolasi yang suram. Tirai jendela ditutup rapat-rapat, menghalau setiap jengkal cahaya matahari siang yang mencoba menerobos masuk. Tidak ada lagi pendar cahaya biru terang dari layar monitor ganda yang biasanya menyala benderang. Komputer utamanya dimatikan secara paksa, kabel-kabelnya dibiarkan menjuntai kusut di lantai, dan bau pengap berpadu dengan aroma keringat serta obat puyer bertebaran di udara.</p>
            <p>Sakra terbaring meringkuk di atas kasurnya yang berantakan. Selimut tebal berwarna abu-abu menutupi seluruh tubuhnya hingga sebatas dada, meski tubuhnya sendiri justru sedang menggigil hebat diserang demam tinggi.</p>
            <p>Suhu tubuhnya melonjak drastis sejak semalam. Kepala Sakra terasa berdenyut-denyut nyeri luar biasa, seolah ada palu besi yang terus menghantam tempurung kepalanya dari dalam. Tenggorokannya kering, sakit setiap kali ia mencoba menelan air liur. Sistem kekebalan tubuhnya akhirnya benar-benar kolaps setelah berbulan-bulan dipaksa bekerja di luar batas kewajaran—begadang tiap malam, kurang tidur kronis, beban pikiran masalah penipuan Bara, tekanan tugas di SMAN 90 Bandung, serta rasa bersalah yang menumpuk.</p>
            <p>Tubuhnya menyerah. Mesin biologis itu akhirnya ngadat total.</p>
            <p>Di luar kamar, pintu berderit pelan saat didorong dari luar. Ibu Sakra melangkah masuk dengan membawa nampan berisi semangkuk bubur hangat dan segelas air putih. Melihat anaknya terbaring tak berdaya di bawah selimut dengan wajah pucat pasi dan bibir pecah-pecah, Ibu menghela napas panjang—napas sarat kekhawatiran seorang ibu yang sudah berkali-kali memperingatkan anaknya agar tidak terlalu memforsir diri.</p>
            <p>Ibu meletakkan nampan di atas meja belajar, lalu duduk di tepi kasur. Ia menempelkan telapak tangannya yang hangat ke dahi Sakra.</p>
            <p>"Astaga, Sakra... badan kamu panas banget kayak kompor," bisik Ibu cemas, segera mengambil handuk kecil di dalam baskom air hangat yang ia bawa untuk dikompreskan ke dahi anaknya. "Mama panggilkan dokter praktik langganan ya? Atau kita ke klinik sekarang? Kamu udah dua hari gak masuk sekolah, MDC-MDCan itu tinggalkan dulu, badan kamu ini udah hancur begini."</p>
            <p>Sakra membuka matanya dengan susah payah. Pandangannya tampak kabur dan berkunang-kunang. Suaranya keluar sangat lemah, serak, nyaris tak berbentuk. "Gak... gak usah, Ma... Sakra cuma butuh istirahat... nanti juga sembuh sendiri..."</p>
            <p>"Istirahat apa kalau dari kemarin kamu cuma tidur meringkuk sambil nahan sakit?" cerca Ibu dengan nada tegas namun menyiratkan kepedihan mendalam. "Uang tabungan hilang, badan sakit-sakitan, sekolah keteteran. Apa sih yang sebenarnya kamu kejar sampai separah ini, Nak?"</p>
            <p>Sakra tidak mampu menjawab. Ia memalingkan wajahnya ke arah dinding, membiarkan air mata panas kembali menetes di pelipisnya. Ibu mengelus punggung Sakra dengan penuh kelembutan, mencoba menenangkan gemetar di tubuh anaknya. Setelah menyuap sesendok bubur yang hampir tak tertelan dan meminumkan obat penurun panas, Ibu berpesan agar Sakra benar-benar beristirahat, lalu meninggalkan kamar itu dalam keadaan remang.</p>
            <p>Suasana kembali sunyi. Sepeninggal ibunya, kamar itu terasa semakin menghimpit dada Sakra.</p>
            <p>Ia merasa menjadi manusia paling gagal di muka bumi. Di usianya yang baru menginjak belasan tahun, ia merasa tidak memiliki apa-apa lagi. Uang tabungannya dirampas penipu, fisiknya tumbang tak berdaya di atas tempat tidur, dan masa depannya di sekolah tampak suram. Dalam kesendirian dan demam tinggi itu, monster paling menakutkan bernama <em>putus asa</em> mulai merayap naik, membisikkan pikiran-pikiran gelap bahwa ia tidak akan pernah sanggup keluar dari lubang kehancuran ini.</p>
            <p>Ponsel pribadi Sakra tergeletak bisu di atas lantai dekat kasur.</p>
            <p>Tiba-tiba, layar ponsel itu menyala terang, memantulkan cahaya hijau dari aplikasi pesan.</p>
            <p><em>Bzzzt... Bzzzt...</em></p>
            <p>Sebuah panggilan suara masuk. Di layar tertera nama yang paling ia rindukan sekaligus paling ia takuti untuk ditemui dalam keadaan menyedihkan seperti ini: <strong>Tasya</strong>.</p>
            <p>Sakra menatap layar ponsel itu dengan pandangan kabur. Hatinya berontak menyuruhnya untuk mengangkat, namun harga diri dan rasa malunya menolak mentah-mentah. Dalam kondisi tak berdaya, mimisan, demam tinggi, dan hancur secara finansial, Sakra merasa dirinya adalah sosok yang sangat menyedihkan. Ia tidak ingin Tasya melihatnya dalam wujud serapuh ini. Ia tidak ingin gadis itu semakin terbebani oleh kondisinya di Bandung.</p>
            <p>Sakra membiarkan panggilan itu berdering hingga mati sendiri.</p>
            <p><em>Satu kali... dua kali... tiga kali.</em></p>
            <p>Ia menutup matanya rapat-rapat, berharap Tasya menyerah dan berhenti menelepon. Namun, dugaannya meleset jauh. Tidak lama setelah panggilan itu terputus, sebuah pesan teks panjang masuk dari Tasya.</p>
            <blockquote>
                <strong>Tasya:</strong> <em>“Sak... angkat teleponnya. Jangan bikin gue gila di sini khawatir setengah mati. Trea barusan ngabari gue, katanya Indra bilang ke anak-anak kalau lu udah dua hari gak masuk sekolah karena tumbang sakit parah di kamar. Angkat, Sak... please.”</em>
            </blockquote>
            <p>Membaca pesan itu, dada Sakra mendadak sesak. Jadi, Trea—sahabat karib mereka yang ada di Bandung—telah mengetahui kondisinya dari Indra dan langsung meneruskannya ke Tasya di Pangandaran. Pertahanan terakhir Sakra runtuh seketika.</p>
            <p>Ponsel di lantai itu berdering lagi. Panggilan suara kedua dari Tasya masuk.</p>
            <p>Dengan tangan yang gemetar hebat dan napas tersenggal-senggal, Sakra merogoh lantai, meraih ponsel tersebut, lalu menggeser tombol hijau ke kanan. Ia mendekatkan benda pipih itu ke telinganya dengan sisa-sisa tenaga yang ia miliki.</p>
            <p>"Halo..." suara Sakra keluar nyaris seperti bisikan parau yang sekarat.</p>
            <p>Di ujung seberang sana, keheningan sempat tercipta selama sedetik sebelum suara Tasya yang bergetar hebat langsung memecah udara.</p>
            <p>"Sakra! Ya Allah... suara lu kenapa jadi kayak orang mau sakaratul maut gitu?!" seru Tasya panik, nada suaranya langsung pecah diselimuti tangis histeris. "Lu sakit apa, Sak? Kenapa lu gak jujur dari kemarin waktu kita telponan? Lu tega banget nutupin ini semua dari gue!"</p>
            <p>Mendengar suara tangis Tasya yang begitu pilu, pertahanan terakhir Sakra jebol. Air mata penyesalan dan kepedihan tumpah ruah membasahi bantal tidurnya.</p>
            <p>"Sya... gue... badan gue hancur..." rintih Sakra terbata-bata, suaranya gemetar menahan sakit di kepala dan rongga dadanya. "Gue demam tinggi... kepala gue pusing banget... uang gue hilang... gue ngerasa gak sanggup lagi, Sya... gue capek..."</p>
            <p>Di kamarnya di Pangandaran, Tasya menangis sejadi-jadinya mendengar rintihan Sakra. Jarak 179 kilometer yang membentang di antara mereka mendadak terasa seperti kutukan paling kejam di dunia. Kekasihnya sedang terbaring lemah, sekarat menahan sakit dan putus asa di kamar kos atau kamarnya di Bandung, sementara ia hanya bisa berdiri terpaku di ujung sambungan telepon tanpa bisa menyentuh, merawat, atau bahkan sekadar mengompres kening pemuda itu secara langsung.</p>
            <p>"Dengerin gue, Sakra! Dengerin suara gue!" potong Tasya dengan nada penuh penekanan, mencoba mengumpulkan sisa-sisa ketegarannya di tengah isak tangis yang menyesakkan dada. "Lu gak boleh nyerah! Lu gak boleh bilang gak sanggup! Kalau lu nyerah, terus siapa lagi yang bakal nemenin gue? Siapa yang mau diajak ngobrol tiap malam?"</p>
            <p>Tasya terus berbicara, mengeluarkan kata-kata penuh cinta, doa, dan dorongan semangat dengan suara yang bergetar hebat. Ia melantunkan kalimat-kalimat penguat, mengingatkan Sakra pada mimpi-mimpi mereka, pada tawa mereka, dan pada fakta bahwa Sakra adalah pusat kekuatan bagi dunianya selama ini.</p>
            <p>Di atas kasurnya di Bandung, di bawah selimut tebal yang membalut tubuhnya yang menggigil, Sakra mendengarkan setiap patah kata yang diucapkan Tasya. Suara gadis itu perlahan-lahan merembes masuk ke dalam relung kesadaran Sakra, bertindak sebagai obat penawar paling mujarab yang menghangatkan sekujur tubuhnya yang dingin.</p>
            <p>Malam itu, di Hari ke-100, di tengah titik terendah dalam hidupnya, Sakra menyadari satu hal yang tak terbantahkan: meskipun dunianya runtuh, uangnya lenyap, dan fisiknya hancur, ia tidak pernah benar-benar sendirian. Suara Tasya di ujung telepon adalah jangkar kuat yang mencegahnya tenggelam lebih dalam ke dasar jurang keputusasaan. Dan di balik keterpurukan itu, benih-benih kebangkitan mulai tumbuh secara perlahan, mempersiapkannya untuk menyambut babak baru saat libur Lebaran tiba di depan mata.</p>
        `
    }
];
