// File: data18.js
const novelData18 = [
    { 
        title: "Bab 20: Hari ke-155 hingga Hari ke-172 — Keputusan Paling Dewasa dan Melodi Perpisahan", 
        content: `
            <p>Lima hari telah berlalu sejak malam di mana Sakra dihantam oleh kenyataan pahit dari lirik lagu <em>Serana</em> dan teguran keras Trea di telepon. Langit Kota Bandung pada Hari ke-155 tampak kelabu, seolah meresonansi kekacauan yang masih mengendap di dasar dada Sakra. Di sebuah kedai kopi bernuansa industrial di kawasan Trunojoyo, aroma biji kopi yang dipanggang berpadu dengan suara rintik hujan yang mulai membasahi aspal.</p>
            <p>Sakra duduk di sudut ruangan, mengaduk <em>americano</em> dinginnya tanpa minat. Kantung matanya masih menghitam, namun ada sorot kepasrahan yang berbeda dari sebelumnya. Di hadapannya, Trea duduk melipat tangan di atas meja. Jaket <em>denim</em> kebesarannya sedikit basah oleh gerimis. Trea menatap sahabat lelakinya itu dengan pandangan menyelidik yang tajam, mencari sisa-sisa ego kekanak-kanakan yang biasanya bercokol di sana.</p>
            <p>"Lu kelihatan kayak gembel yang baru diusir dari kosan, Sak," buka Trea tanpa basa-basi, menyesap <em>latte</em> hangatnya.</p>
            <p>Sakra tersenyum getir, menatap pantulan dirinya di genangan air meja. "Gua emang ngerasa kayak gembel, Tre. Gembel yang baru sadar kalau istana yang dia bangun ternyata malah menindas orang di dalamnya."</p>
            <p>Trea menghela napas panjang, merilekskan postur tubuhnya. "Baguslah kalau lu udah sadar. Gua sengaja ngajak lu ketemu langsung hari ini bukan buat ngomelin lu lagi. Lu udah cukup hancur seminggu ini. Gua cuma mau mastiin otak lu udah jalan dengan bener. Lu udah ngasih Tasya ruang?"</p>
            <p>"Udah," jawab Sakra pelan namun mantap. "Gua ngurangin intensitas chat. Gua gak lagi maksa dia buat nelpon kalau dia lagi capek. Gua biarin dia napas. Dan... gua juga udah beresin beberapa hal di sini."</p>
            <p>Sakra memang tidak berbohong. Dalam lima hari terakhir, ia melakukan perombakan besar dalam hidupnya. Ia memblokir permanen nomor Bara dan keluar dari semua grup joki game toksik yang merusak mental dan fisiknya. Ia menghampiri ibunya di dapur, meminta maaf sambil memeluk wanita paruh baya itu karena selama ini terlalu keras kepala dan sering mengabaikan nasihat kesehatannya. Di sekolah, ia membelikan batagor porsi besar untuk Indra dan Habib, meminta maaf secara jantan karena sempat menjadi sahabat yang egois dan pemarah selama beberapa bulan terakhir.</p>
            <p>Mendengar itu, Trea mengangguk puas. "Itu baru Sakra yang gua kenal. Terus, ke depannya lu mau gimana sama Tasya?"</p>
            <p>Pertanyaan Trea menggantung di udara, beradu dengan suara musik <em>indie</em> yang mengalun dari pelantang suara kafe. Sakra menatap jalanan yang basah, mencari jawaban yang sebenarnya sudah mulai mengakar di dalam kepalanya, namun masih terlalu menyakitkan untuk diucapkan.</p>
            <p>"Gua belum tahu, Tre. Gua cuma mau mastiin dia gak ngerasa terbebani lagi."</p>
            <p><strong>Hari ke-160</strong> tiba dengan kesunyian yang mencekam di dalam kamar Sakra.</p>
            <p>Malam itu, di hadapan meja belajarnya, Sakra membuka ruang obrolannya dengan Tasya di WhatsApp. Ia melihat foto profil Tasya—gadis dengan senyum paling manis yang pernah ia temui di bawah langit Pangandaran. Jari-jemari Sakra mulai mengetik di atas layar, merangkai sebuah pesan yang sangat panjang.</p>
            <blockquote>
                <strong>Sakra:</strong> <em>“Sya, gua mau minta maaf buat semuanya. Gua baru sadar kalau effort gua selama ini malah bikin lu tertekan. Tolong jangan pernah ngerasa berutang budi sama gua, Sya. Gua ngelakuin semua itu murni karena gua sayang sama lu. Lu gak perlu balas apa-apa. Cukup lu ada di sana, tersenyum, dan jadi Tasya yang gua kenal, itu udah lebih dari cukup buat gua. Kita mulai semuanya dari awal ya? Tanpa ada beban, tanpa ada perasaan jomplang.”</em>
            </blockquote>
            <p>Sakra membaca ulang paragraf yang baru saja ia ketik. Matanya memanas. Pesan itu terdengar sangat sempurna, sangat tulus.</p>
            <p>Namun, tepat sebelum jempolnya menekan tombol kirim, logika dan kedewasaannya yang baru terbentuk mengambil alih. Ia menatap lekat-lekat kata-kata di layar itu.</p>
            <p>Sebuah kesadaran brutal menghantamnya: tidak peduli seberapa tulus ia meyakinkan Tasya bahwa ia tidak menuntut balasan, rasa bersalah itu tidak akan pernah hilang. Selama ia masih menyandang status sebagai "pacar", selama itu pula Tasya akan merasa memiliki kewajiban moral untuk mengimbangi usahanya. Status itulah yang menjadi jangkar dari segala rasa <em>insecure</em> kekasihnya. Mengirim pesan ini hanya akan menjadi bentuk pemaksaan baru, seolah ia menyuruh Tasya untuk menelan rasa bersalahnya dalam-dalam.</p>
            <p>Dengan tangan yang gemetar dan rahang yang mengeras menahan tangis, Sakra menekan tombol <em>backspace</em>.</p>
            <p>Satu per satu, huruf demi huruf dari pesan panjang itu terhapus. Ia menghapus semuanya hingga kotak pesan kembali kosong melompong. Sakra meletakkan ponselnya, menenggelamkan wajahnya di lipatan lengan di atas meja, dan membiarkan air mata kekalahannya menetes di keheningan malam. Ia sadar, ada pesan-pesan di dunia ini yang memang ditakdirkan untuk tidak pernah terkirim, karena menahannya adalah bentuk pengorbanan yang jauh lebih besar daripada mengungkapkannya.</p>
            <p>Lima hari kemudian, tepat di <strong>Hari ke-165</strong>, Sakra duduk sendirian di gazebo kayu dekat sanggar Pramuka SMAN 90 Bandung. Angin sore bertiup kencang, menggugurkan daun-daun kering ke atas pangkuannya.</p>
            <p>Di tempat inilah dulu ia sering tertawa bersama Indra dan Habib. Di tempat ini pula ia sering menatap langit, membayangkan Tasya di pesisir selatan sana.</p>
            <p>Sakra memejamkan mata. Di dalam keheningan sore itu, ia mengambil sebuah kesimpulan paling jernih dan paling pahit dalam hidupnya yang baru berusia delapan belas tahun. Ia mencintai Tasya dengan seluruh jiwa dan raganya. Ia rela menumpahkan darah, keringat, dan waktunya demi gadis itu. Namun, jika cintanya justru menjadi penjara yang mencekik senyum Tasya, maka cara terbaik untuk mencintai gadis itu saat ini bukanlah dengan memaksakan diri untuk bertahan.</p>
            <p>Cara tertinggi untuk mencintai Tasya saat ini adalah dengan melepaskannya. Membebaskannya dari status yang membebaninya.</p>
            <p>Keputusan itu sudah bulat. Sebuah keputusan paling dewasa yang harus ditebus dengan kehancuran hatinya sendiri.</p>
            <p><strong>Hari ke-168</strong> merayap datang membawa hawa dingin yang menusuk tulang. Jarum jam tepat menunjuk pukul 22.00 WIB.</p>
            <p>Sakra duduk di lantai kamarnya, bersandar pada tepi kasur. Ia menarik napas dalam-dalam berulang kali, mencoba menormalkan detak jantungnya yang bergemuruh gila-gilaan. Setelah merasa cukup kuat, ia menekan nomor Tasya.</p>
            <p>Panggilan itu tersambung.</p>
            <p>"Halo, Sak..." suara Tasya terdengar di ujung sana. Sangat pelan, sangat berhati-hati, dan menyiratkan kelelahan batin yang belum juga usai.</p>
            <p>"Halo, Sya," balas Sakra. Ajaibnya, tidak ada getar kemarahan, kecemburuan, atau ego dalam suaranya malam ini. Suara Sakra terdengar luar biasa lembut, hangat, dan menenangkan—persis seperti Sakra di bulan-bulan pertama mereka bertukar cerita sebagai sahabat.</p>
            <p>Mereka berbicara tentang hal-hal kecil malam itu. Tentang cuaca di Bandung, tentang laporan OSIS Tasya di Pangandaran, tentang kucing liar yang sering mampir ke rumah Tasya. Namun, di balik percakapan ringan itu, ada gajah besar di dalam ruangan yang sama-sama mereka hindari, hingga akhirnya Sakra memutuskan untuk membukanya dengan sangat hati-hati.</p>
            <p>"Sya," panggil Sakra lembut.</p>
            <p>"Iya, Sak?"</p>
            <p>"Lu tahu kan kalau gua sayang banget sama lu?"</p>
            <p>Tasya terdiam di ujung sana. Terdengar suara tarikan napas yang bergetar. "Aku tahu, Sak... aku tahu banget."</p>
            <p>"Dan lu juga tahu, gua gak bakal pernah rela liat lu sedih, apalagi kalau kesedihan itu sumbernya dari gua sendiri," lanjut Sakra, matanya mulai memanas, namun ia menahan suaranya agar tidak pecah. "Gua udah mikirin ini matang-matang, Sya. Tentang kita. Tentang jarak 179 kilometer ini. Tentang beban yang lu rasain selama ini."</p>
            <p>Terdengar isakan kecil dari seberang sana. Tasya sudah mulai menangis.</p>
            <p>"Jangan nangis, Sya. Sumpah, gua nelpon bukan buat bikin lu nangis malam ini," bujuk Sakra dengan senyum pedih yang tidak bisa dilihat oleh Tasya. "Gua cuma mau bilang... lu gak perlu lagi ngerasa jomplang. Lu gak perlu lagi ngerasa bersalah atau bingung gimana cara bales <em>effort</em> gua. Lu bebas dari semua perasaan itu sekarang."</p>
            <p>"Sak... maksud lu apa?" suara Tasya pecah, panik dan ketakutan mulai merayap naik.</p>
            <p>"Besok kita ngobrol lagi ya, Sya. Sekarang lu tidur yang nyenyak. Jangan <em>overthinking</em>. Gua cuma pengen lu tahu, apa pun yang terjadi, lu tetap cewek paling hebat yang pernah gua kenal."</p>
            <p>Sakra memutus panggilan itu dengan sangat lembut, tidak membiarkan perdebatan terjadi. Ia butuh malam ini untuk membiarkan Tasya mencerna arah pembicaraan mereka, mempersiapkan mental gadis itu untuk ledakan sesungguhnya esok hari.</p>
            <p>Lalu tibalah <strong>Hari ke-169</strong>. Sebuah hari yang akan terukir permanen sebagai luka paling indah dalam sejarah mereka.</p>
            <p>Sore itu, hujan turun rintik-rintik di Pangandaran. Di dalam kamar kosnya, Tasya duduk meringkuk memeluk lutut. Di sampingnya, Trea duduk merangkul bahu Tasya dengan erat. Trea secara khusus meminta izin pada keluarganya untuk pergi ke Pangandaran akhir pekan ini. Ia tahu persis apa yang akan terjadi hari ini, dan ia tahu Tasya tidak akan sanggup menghadapinya sendirian.</p>
            <p>Ponsel Tasya berdering. Panggilan <em>video call</em> dari Sakra.</p>
            <p>Dengan tangan gemetar, Tasya menggeser tombol hijau. Di layar, wajah Sakra terlihat sangat tenang. Latar belakangnya adalah langit senja Kota Bandung yang mulai menggelap dari jendela kamarnya.</p>
            <p>"Halo, Sya. Hai, Tre. Makasih ya udah nemenin Tasya di sana," sapa Sakra membuka percakapan, tersenyum tipis ke arah layar.</p>
            <p>Trea hanya mengangguk pelan dari samping Tasya, matanya menyiratkan rasa hormat yang luar biasa besar pada kedewasaan Sakra.</p>
            <p>"Sak..." panggil Tasya, air matanya sudah menggenang di pelupuk mata.</p>
            <p>Sakra menatap layar itu lekat-lekat. Ia merekam setiap inci wajah Tasya di dalam ingatannya. "Sya, ingat obrolan kita semalam? Tentang beban lu, tentang perasaan jomplang lu?"</p>
            <p>Tasya mengangguk kaku, air matanya mulai menetes.</p>
            <p>"Gua udah mutusin, Sya," ucap Sakra, suaranya terdengar sangat mantap meski hatinya hancur berkeping-keping. "Cara satu-satunya supaya lu bisa napas lega, supaya lu gak ngerasa punya utang budi lagi sama gua... adalah dengan ngelepasin ikatan ini. Kita kembali jadi dua orang yang berjalan sendiri-sendiri ya, Sya. Kita sudahi status pacaran ini sampai di sini."</p>
            <p>Tangis Tasya meledak seketika. "Enggak, Sak... please, enggak! Aku masih sayang sama lu! Aku gak mau putus! Aku minta maaf kalau aku banyak kurangnya, aku minta maaf kalau aku egois!" teriak Tasya histeris, mendekatkan wajahnya ke layar ponsel, mencoba menggapai Sakra yang berada sejauh 179 kilometer darinya.</p>
            <p>Melihat Tasya menangis sehisteris itu, pertahanan Sakra akhirnya runtuh. Air matanya mengalir deras membasahi pipinya, namun ia memaksakan diri untuk tetap tersenyum di depan layar. Ia menggeleng pelan.</p>
            <p>"Ini bukan soal lu kurang, Sya. Lu sempurna. Justru karena gua terlalu sayang sama lu, gua gak bisa ngebiarin lu terus-terusan hancur karena tekanan dari hubungan ini. Lu berhak bahagia tanpa ngerasa bersalah tiap harinya. Lu berhak bebas."</p>
            <p>Sakra meraih <em>mouse</em> di mejanya, mengeklik daftar putar musiknya. Alunan melodi gitar akustik yang sangat menyayat hati dari intro lagu <strong>"So Far Away"</strong> milik <em>Avenged Sevenfold</em> perlahan terdengar mengalun menjadi latar belakang percakapan perpisahan mereka. Lagu tentang kehilangan yang begitu mendalam, namun harus direlakan.</p>
            <p><em>“How do I live without the ones I love? Time still turns the pages of the book its burned...”</em></p>
            <p>"Dengerin lagu ini, Sya," bisik Sakra di sela-sela tangisnya, menatap lekat mata Tasya di layar. "Sejauh apa pun kita nanti, 179 kilometer ini udah ngajarin gua banyak hal. Makasih buat waktunya, makasih buat tawa lu yang sempet jadi alarm tidur gua, makasih buat semuanya. Berhenti nangis ya... gua pamit."</p>
            <p>"Sakra, jangan ditutup! Sakra, please!" jerit Tasya di sela isakannya yang mencekik tenggorokan.</p>
            <p>"Jaga diri baik-baik di Pangandaran, Inces. Sampai ketemu di versi kita yang lebih baik."</p>
            <p>Layar mendadak gelap. Panggilan itu ditutup dari pihak Sakra.</p>
            <p>Di Pangandaran, ponsel itu terlepas dari genggaman Tasya, jatuh ke atas kasur. Tasya menjerit histeris, menutupi wajahnya dengan kedua tangan. Rasa sakit kehilangan orang yang paling ia cintai menghantamnya bersamaan dengan kenyataan bahwa orang tersebut melepaskannya justru demi menyelamatkan mentalnya.</p>
            <p>Trea langsung merengkuh tubuh Tasya yang bergetar hebat. Ia memeluk sahabatnya itu dengan sangat erat, membiarkan Tasya menangis meraung-raung di ceruk lehernya. Trea ikut meneteskan air mata, menjadi saksi bisu dari akhir sebuah cinta remaja yang terlalu besar dan terlalu menyakitkan untuk disatukan oleh jarak.</p>
            <p>Di Bandung, Sakra menjatuhkan wajahnya ke atas meja komputernya. Ia menangis sejadi-jadinya, meluapkan seluruh rasa sakit yang selama ini ia tahan mati-matian. Lagu <em>So Far Away</em> terus berputar menemani kehancurannya di Hari ke-169. Ia telah kehilangan dunianya, namun ia tahu, ia telah melakukan hal yang paling benar.</p>
            <p>Tiga hari berlalu dengan kecepatan yang terasa tidak nyata. Pada <strong>Hari ke-172</strong>, matahari sore bersinar terang menyinari Kota Bandung, menghalau sisa-sisa awan kelabu.</p>
            <p>Di sebuah warung kopi sederhana di seberang gerbang SMAN 90 Bandung, asap dari gelas-gelas kopi hitam mengepul ke udara. Sakra duduk di bangku kayu panjang, mengenakan jaket <em>hoodie</em> hitam kesayangannya. Di samping kanan dan kirinya, Indra dan Habib duduk menemani dengan setia.</p>
            <p>Tak lama kemudian, sebuah motor matik berhenti di depan warung. Trea—yang baru saja tiba dari perjalanan jauhnya dari Pangandaran—membuka helmnya, merapikan rambut pendeknya, dan berjalan mendekati meja mereka.</p>
            <p>Trea duduk tepat di hadapan Sakra. Ia menatap wajah sahabat lelakinya itu. Wajah Sakra memang tampak lelah, namun ada seberkas cahaya kelegaan dan kedamaian yang sudah lama hilang dari sana. Mata Sakra memancarkan ketenangan.</p>
            <p>"Gimana keadaan dia, Tre?" tanya Sakra pelan.</p>
            <p>"Hancur," jawab Trea jujur tanpa ditutup-tutupi. "Tapi dia bakal baik-baik aja, Sak. Dia butuh waktu buat sembuh, sama kayak lu. Tapi lu udah ngasih dia kesempatan buat napas lagi."</p>
            <p>Indra merangkul pundak Sakra dengan keras dari samping. "Lu udah ngelakuin hal yang bener, Kra. Lu cowok paling <em>gentle</em> yang pernah gua kenal. Ngelepasin orang yang lu sayang pas lu lagi sayang-sayangnya itu bukan perkara gampang. Gua bangga sama lu."</p>
            <p>Habib ikut menepuk bahu Sakra dari sisi yang lain, tersenyum lebar menampakkan giginya. "Bener kata si Indra. Sekarang, lu balik lagi jadi Sakra yang kita kenal. Sakra si Ketua MDC yang waras, yang gak gampang darah tinggi, dan yang siap traktir kita batagor tiap sore."</p>
            <p>Trea tersenyum hangat dari seberang meja. Ia mengulurkan tangannya, meremas punggung tangan Sakra dengan penuh empati persahabatan. "Lu hebat, Sakra. Beneran hebat. Proses lu tumbuh dari cowok yang maksain egonya jadi laki-laki yang berani ngorbanin perasaannya sendiri... itu luar biasa. Tasya beruntung pernah punya lu, dan kita semua beruntung punya lu sebagai sahabat."</p>
            <p>Sakra menunduk, menatap cangkir kopinya. Sebuah senyum tipis—senyum yang benar-benar tulus dan bebas dari segala beban—akhirnya merekah di bibirnya. Ia mengangkat kepalanya, menatap Indra, Habib, dan Trea secara bergantian.</p>
            <p>Di tengah kehangatan pelukan kawan sebaya dan aroma kopi sore itu, Sakra menyadari bahwa angka 179 kilometer tidak lagi menjadi monster yang menakutkan baginya. Jarak itu telah mengajarkannya arti dari <em>give and take</em>, tentang batas antara cinta dan obsesi, dan tentang keberanian untuk melepaskan genggaman saat tangan yang kita pegang sudah mulai berdarah. Di Hari ke-172, Sakra Sirotunawal menutup buku masa lalunya, menarik napas panjang menikmati udara kebebasan, dan siap melangkah menyongsong hari esok dengan jiwa yang baru.</p>
        `
    }
];
