// File: data9.js
const novelData9 = [
    { 
        title: "Bab 11: Hari ke-115 — Penjaga Kereta Terakhir", 
        content: `
            <p>Libur Lebaran yang berjalan begitu hangat dan penuh tawa seolah terbang begitu saja ditiup angin kencang. Waktu liburan sekolah yang diberikan semesta kepada mereka teramat sangat singkat untuk ukuran dua orang yang haus akan kebersamaan fisik. Hari ke-115 tiba dengan membawa kenyataan pahit yang harus ditelan mentah-mentah tanpa bisa ditawar: masa cuti keluarga Tasya telah habis, dan gadis itu harus kembali memboyong barang-barangnya ke Pangandaran untuk melanjutkan kembali rutinitas sekolahnya di SMAN 81.</p>
            <p>Pagi itu, di Stasiun Bandung yang dipadati oleh arus balik penumpang kereta api lokal jurusan selatan, suasana terasa begitu berat dan menyesakkan dada. Udara pagi stasiun berbau asap diesel yang bercampur dengan keringat para penumpang yang berdesakan di peron.</p>
            <p>Sakra berdiri kaku di atas peron stasiun, mengenakan jaket <em>hoodie</em> hitam yang kemarin sempat ia pinjamkan pada Tasya. Di hadapannya, Tasya berdiri sambil merapikan tali ransel di punggungnya, sementara suara pengeras suara stasiun silih berganti mengumumkan jadwal kedatangan dan keberangkatan kereta antarkota. Wajah Tasya tampak muram, menunduk dalam-dalam untuk menyembunyikan sisa-sisa air mata yang sempat tumpah di dalam taksi dalam perjalanan menuju stasiun.</p>
            <p>"Udah ya, Sak... jangan diantar sampai masuk ke dalam gerbong keretanya ya," ucap Tasya lirih, suaranya bergetar menahan tangis. Ia mendongak, mencoba memasang senyum tipis paling tegar di bibirnya meski sepasang matanya sudah basah oleh genangan air mata. "Nanti lu makin sedih pas balik sendirian keluar stasiun."</p>
            <p>Sakra menelan ludah susahnya, merasakan rongga dadanya kembali menyempit bagai diikat sabuk besi. Bayangan hari kemarin saat mereka duduk bersandar di bukit utara Bandung masih terasa hangat, namun kini realita kembali merenggutnya secara paksa. "Iya, Sya... hati-hati di jalan. Nanti sampai sana langsung kabari gue. Kalau kereta udah jalan, jangan lupa istirahat karena semalaman lu pasti kurang tidur."</p>
            <p>"Iya, bawel," jawab Tasya lembut, lalu meraih tangan Sakra dan menggenggamnya erat-erat untuk terakhir kalinya sebelum ia berbalik melangkah menuju pintu masuk gerbong ekonomi AC.</p>
            <p>Sakra mematung di atas peron stasiun. Ia menyaksikan langkah kaki Tasya semakin menjauh, masuk ke dalam gerbong, lalu melambaikan tangan dari balik kaca jendela kereta yang mulai bergeser pelan meninggalkan rel peron. Kereta itu bergerak perlahan, membawa serta separuh jiwa Sakra kembali meluncur menjauh sejauh 179 kilometer menuju pesisir selatan Jawa Barat.</p>
            <p>Saat gerbong terakhir kereta itu benar-benar hilang dari pandangan di balik tikungan rel, Sakra merasakan kehampaan yang luar biasa menghantam dadanya. Kembali ke rutinitas lama—kembali menatap layar ponsel tanpa kehadiran fisik Tasya di kota yang sama—ternyata jauh lebih menyakitkan daripada sebelum mereka bertemu.</p>
            <p>Dua hari berselang usai kepulangan Tasya ke Pangandaran, akumulasi beban hidup yang selama ini ditahan oleh Sakra akhirnya menagih bayarannya secara kontan tanpa ampun.</p>
            <p>Hari itu, matahari bersinar terik membakar lapangan upacara SMAN 90 Bandung. Sakra sedang memimpin latihan baris-berbaris dan penataan perlengkapan inventaris di sanggar MDC Pramuka. Pembina ambalan memberikan target tambahan yang cukup ketat: seluruh laporan digital, rekapitulasi data anggota baru, dan arsip semester ini harus selesai diverifikasi dalam waktu dua hari ke depan tanpa pengecualian.</p>
            <p>Sakra, yang masih memaksakan diri bekerja keras usai kelelahan liburan dan kurang tidur, mondar-mandir di sanggar dengan wajah sepucat kapas. Ia bahkan melewatkan jam makan siang karena harus membereskan server lokal MDC yang sempat <em>error</em>. Kepalanya mulai berdenyut-denyut nyeri hebat, dan penglihatannya mendadak buram berkunang-kunang.</p>
            <p>Ia mencoba bertahan, memegang erat pinggiran meja kayu panjang untuk menjaga keseimbangannya agar tidak terjatuh. Namun, dunia di sekelilingnya mendadak berputar kencang seratus delapan puluh derajat. Suara-suara bising anak-anak pramuka di luar sayup-sayup meredup, berubah menjadi dengung panjang yang memekakkan telinga.</p>
            <p><em>Bruk!</em></p>
            <p>Tubuh Sakra ambruk tak berdaya ke lantai kayu sanggar dengan suara keras, kehilangan kesadaran seketika.</p>
            <p>"Eh! Sakra pingsan! Ya Allah, Kak Sakra!" teriakan panik meluncur histeris dari mulut salah satu anggota junior MDC yang melihat kejadian tersebut.</p>
            <p>Tidak butuh waktu lama, berita kolapsnya Ketua MDC itu menyebar cepat ke seluruh penjuru sekolah. Indra dan Habib yang sedang berada di ruang kelas langsung berlari kencang menuju sanggar Pramuka. Dengan bantuan beberapa pengurus ambalan, tubuh Sakra yang lemas, dingin, dan basah oleh keringat dingin digotong buru-buru menuju ruang UKS sekolah.</p>
            <p>Sesampainya di UKS, aroma minyak angin dan obat merah langsung menyengat tajam. Indra menyuruh anak-anak junior keluar, sementara Habib sibuk mengoleskan minyak kayu putih ke pelipis dan telapak tangan Sakra. Petugas medis sekolah datang memeriksa tekanan darah Sakra dan langsung menggelengkan kepala dengan ekspresi prihatin.</p>
            <p>"Ini anak keracunan aktivitas dan kelelahan kronis. Tekanan darahnya drop banget, dehidrasi berat, dan lambungnya kosong melompong. Kalau dipaksakan terus begini tanpa istirahat total, organ vitalnya yang bakal kena," tegur petugas UKS dengan nada tegas penuh peringatan.</p>
            <p>Indra berdiri di samping tempat tidur UKS, mengepalkan tangan kanannya dengan wajah kesal campur cemas luar biasa. Ia menatap wajah Sakra yang terbaring memejamkan mata dengan bibir sepucat kertas.</p>
            <p>"Udah dibilangin berkali-kali juga bandel sih ni anak," gerutu Indra penuh emosi. "Kerjaannya melulu mikirin tugas MDC, mikirin anak orang di Pangandaran, sampai badannya sendiri disiksa kayak kuda beban!"</p>
            <p>Tepat saat itu, pintu ruang UKS terdorong terbuka dengan kasar dari luar. Trea—yang kebetulan mendapat izin dispensasi dari sekolahnya untuk datang ke SMAN 90 guna mengantar dokumen titipan—berdiri di ambang pintu dengan napas memburu dan wajah panik luar biasa. Trea baru saja dihubungi oleh Habib lewat pesan WhatsApp panik beberapa menit lalu.</p>
            <p>Trea melangkah cepat mendekati ranjang UKS, menatap tajam ke arah Sakra yang tak sadarkan diri, lalu menoleh marah ke arah Indra dan Habib.</p>
            <p>"Gila ya kalian! Kenapa Sakra bisa pingsan parah begini sampai masuk UKS?!" suara Trea bergetar hebat, memendam amarah sekaligus rasa takut yang mendalam sebagai sahabat yang paling mengerti batas fisik Sakra. "Dia itu baru aja pulih dari sakit parah bulan lalu, kenapa dibiarin kerja rodi lagi di Pramuka?!"</p>
            <p>"Kita udah larang keras, Tre, tapi dia-nya keras kepala banget kayak batu karang!" bela Habib pasrah. "Dia ngejar deadline laporan MDC biar gak keteteran."</p>
            <p>Trea menghela napas panjang, menahan air mata kekesalannya yang mendesak naik ke pelupuk mata. Ia meraih sebuah kursi plastik, duduk di samping ranjang Sakra, lalu menggenggam jemari Sakra yang terasa dingin terkulai lemas.</p>
            <p>Di tengah ketidaksadaran itu, Sakra tidak tahu bahwa tubuhnya kembali memberikan sinyal peringatan paling keras dari semesta. Pingsannya Sakra di ruang MDC hari itu bukan sekadar kelelahan biasa; itu adalah akumulasi dari tekanan mental, obsesi kesempurnaan, dan siksaan rindu akibat jarak 179 kilometer yang terus menggerogoti fisiknya dari dalam. Dan kabar buruk tentang kolapsnya Sakra ini tidak bisa disembunyikan lagi—ia pasti akan segera sampai ke telinga Tasya di Pangandaran, memicu badai kepanikan baru yang siap meretakkan pertahanan rapuh sang kekasih di seberang sana.</p>
        `
    }
];
