// File: data8.js
const novelData8 = [
    { 
        title: "Bab 10: Hari ke-110 — Ketupat dan Senja", 
        content: `
            <p>Dua minggu telah berlalu sejak malam di mana suara Tasya lewat sambungan telepon menjadi jangkar paling kokoh yang menyelamatkan Sakra dari jurang keputusasaan. Suhu tubuhnya telah kembali normal, pendarahan hidung akibat kelelahan ekstrem telah berhenti, dan lambat laun, warna kemerahan yang sehat kembali menghiasi wajah mudanya. Di bawah tatapan waswas sang Ibu di rumah serta omelan setengah mati dari Indra dan Habib di lingkungan SMAN 90 Bandung, Sakra bangkit kembali dari titik nadir kehidupannya. Ia telah menutup akun joki gamenya untuk selamanya, membuang jauh-jauh nomor Bara dari daftar kontaknya tanpa penyesalan, dan memilih untuk mengalihkan sisa energi dan fokusnya pada hal-hal yang jauh lebih esensial: menjaga kesehatan fisik, memperbaiki nilai-nilai pelajarannya yang sempat merosot, serta merampungkan persiapan akhir menyambut hari raya Idulfitri.</p>
            <p>Kini, kalender digital di sudut layar laptopnya menunjukkan Hari ke-110. Suasana bulan suci Ramadan yang penuh refleksi telah berpulang, digantikan oleh kumandang takbir, tahmid, dan tahlil yang bersahut-sahutan merdu dari menara-menara masjid di penjuru Kota Bandung sejak semalam. Pagi hari Lebaran tiba dengan membawa cuaca yang sangat cerah, sejuk, dan menyegarkan khas dataran tinggi Bandung, menyebarkan aroma harum opor ayam kuah santan kental, ketupat yang baru saja diangkat dari rebusan, serta sambal goreng ati petai yang menguap memenuhi dapur-dapur rumah warga.</p>
            <p>Namun, di tengah semarak perayaan hari kemenangan tersebut, ada satu hal yang paling dinantikan oleh Sakra—sebuah momen yang sudah ia bayangkan dan hitung hari demi harinya sejak berminggu-minggu lalu: kepulangan Tasya ke Kota Bandung.</p>
            <p>Keluarga Tasya memutuskan untuk mudik sejenak ke rumah lama mereka di Bandung demi bersilaturahmi dengan kerabat, sanak saudara, serta tetangga lama yang merindukan kehadiran mereka. Jarak sejauh 179 kilometer yang biasanya menjadi tembok pembatas yang kejam kini runtuh lebur seketika oleh momentum hari raya. Tasya kembali ke kota ini, berdiri di tanah yang sama, menghirup udara dingin yang sama dengan Sakra, tanpa harus terhalang oleh layar kaca ponsel berukuran enam inci yang dingin.</p>
            <p>Pukul sepuluh pagi, di sebuah rumah makan keluarga bernuansa tradisional di kawasan Alun-Alun Bandung yang dipadati oleh warga berkostum lebaran usai melaksanakan salat Idulfitri, sebuah pertemuan yang sudah lama diimpikan akhirnya terwujud nyata.</p>
            <p>Sakra duduk di kursi panjang meja kayu berpelitur cokelat tua, mengenakan kemeja koko putih bersih bertekstur lembut yang sangat kontras dengan kulitnya yang mulai kembali segar. Jantungnya berdegup kencang bukan main—jauh lebih kencang dibandingkan saat ia harus menghadapi barisan kodingan server yang <em>error</em> di tengah malam atau ujian akhir semester yang menegangkan. Sepasang matanya menatap lekat ke arah pintu masuk restoran yang terus dilalui oleh lalu-lalang pengunjung yang datang silih berganti.</p>
            <p>Tak lama kemudian, di antara kerumunan orang-orang yang mengenakan pakaian serba baru, sesosok gadis berbalut gamis elegan berwarna <em>sage green</em> dengan kerudung pasmina senada melangkah masuk ke dalam area restoran. Ia menebar pandangan ke sekeliling, mencari-cari meja yang dimaksud. Tasya.</p>
            <p>Begitu sepasang mata mereka saling bertemu pandang, dunia di sekitar mereka seolah melambat, meredupkan segala kebisingan kota menjadi keheningan yang magis. Tidak ada lagi angka 179 kilometer di kepala mereka. Tidak ada lagi rasa bersalah akibat <em>insecure</em> atau beban pengorbanan yang tak kasat mata. Tasya berdiri nyata di hadapannya, tersenyum lebar dengan mata yang berbinar basah oleh air mata kebahagiaan. Tanpa memperdulikan tatapan penuh senyum dari para pengunjung lain di sekitar meja, Tasya langsung mempercepat langkah kakinya, meninggalkan barang bawaannya sejenak, dan menghampiri meja Sakra.</p>
            <p>"Sakra!" panggil Tasya riang, suaranya melengking manis menembus riuhnya suasana restoran.</p>
            <p>Sakra bangkit berdiri seketika dari kursinya dengan gerakan refleks yang cepat. Belum sempat ia menyusun kata-kata sambutan yang romantis di dalam kepalanya, Tasya sudah merangsek maju dan menyambutnya dalam sebuah pelukan hangat—sebuah pelukan rindu yang selama berbulan-bulan tertahan oleh jarak dan benteng pertahanan batin mereka. Wangi khas parfum vanila lembut milik Tasya menguar seketika di penciuman Sakra, mengirimkan sengatan kehangatan yang membuncah ke seluruh rongga dadanya. Sakra membalas pelukan itu perlahan namun pasti, merengkuh punggung Tasya erat-erat di hadapan publik, menikmati detik-detik di mana semesta seolah memberikan izin bagi mereka untuk bersatu tanpa sekat.</p>
            <p>"Lu kurusan, Sak," bisik Tasya lembut tepat di dekat telinga Sakra saat mereka perlahan melepaskan pelukan tersebut, matanya menatap lekat wajah Sakra dengan senyuman penuh kelegaan yang tulus. "Tapi untung sekarang udah segar lagi, gak kayak waktu ditelepon malam-malam kemarin yang hampir kayak orang mau sakaratul maut."</p>
            <p>Sakra tertawa kecil, suara tawanya terdengar renyah dan lepas. Ia mengusap tengkuknya sendiri karena merasa salah tingkah. "Gara-gara lu cerewet banget sih di telepon tiap malam nyuruh gua istirahat, makanya gua jadi cepet sembuh dan nurut sama nasihat mama."</p>
            <p>Namun, kebahagiaan reuni dua sejoli yang baru saja melepas rindu itu tidak dibiarkan berdua saja terlalu lama. Dari arah pintu utama restoran, suara tawa melengking yang sangat akrab tiba-tiba memecah suasana, disusul oleh kemunculan sesosok gadis berjaket <em>denim</em> bergaya <em>oversized</em> dengan langkah kaki yang energetik.</p>
            <p>"Woi! Udah peluk-pelukannya? Mentang-mentang LDR berbulan-bulan, ketemu langsung nempel kayak perangko gak tau malu di tempat umum!" seru Trea nyaring tanpa filter, melangkah mendekati meja mereka sambil menjinjing kantong plastik berukuran besar berisi oleh-oleh khas pesisir Pangandaran.</p>
            <p>Trea—sahabat karib Tasya sejak masa SMP sekaligus sahabat perempuan terdekat Sakra di Bandung—langsung menarik kursi kayu kosong dan duduk di hadapan mereka berdua tanpa diundang.</p>
            <p>Suasana meja makan itu seketika berubah menjadi arena reuni kecil yang sangat hidup, bising, penuh canda tawa, dan hingar-bingar khas anak muda. Tidak ada Indra ataupun Habib di sana; hari itu, panggung kecil itu sepenuhnya milik ketiganya.</p>
            <p>"Eh, Trea! Jahat banget lu suka banget ngabisin momen orang dari tadi," protes Tasya sambil tertawa renyah, merengkuh pundak sahabatnya itu dengan gemas sementara pipinya merona merah.</p>
            <p>"Ih, emangnya gua patung hiasan restoran yang bisa dicuekin begitu aja dari tadi? Gua kan pengen lihat juga seberapa bucin anak-anak MDC MDC ini setelah sebulan hampir mati kelaparan gara-gara mikirin cinta jarak jauh," balas Trea sewot bercanda, lalu menoleh tajam dengan tatapan menyelidik ke arah Sakra. "Lu ya, Sak, denger-denger dari grup, kemarin pas sakit parah lu hampir gak mau dibawa ke rumah sakit gara-gara begadang? Mau cari mati sebelum nikah, hah?"</p>
            <p>Sakra mendelik ke arah Trea. "Sembarangan kalau ngomong, Tre. Mulut emang gak bisa dijaga kalau dikasih makan ketupat."</p>
            <p>Pertemuan bertiga antara Sakra, Tasya, dan Trea di hari raya Idulfitri itu mendadak menjelma menjadi babak paling membahagiakan. Mereka menghabiskan waktu seharian penuh berkeliling kawasan Alun-Alun Bandung, berjalan kaki menyusuri Jalan Asia Afrika yang bersejarah, berfoto bersama di bawah terik matahari pagi yang hangat, bernostalgia menceritakan kebiasaan-kebiasaan lama saat mereka masih satu sekolah dulu, hingga sore harinya bertandang ke rumah lama keluarga Tasya untuk menyantap hidangan ketupat dan opor buatan ibu Tasya.</p>
            <p>Menjelang magrib, Trea pamit pulang lebih dulu karena harus membantu keluarganya menerima tamu di rumah. Hari pertama Lebaran pun berangsur-angsur malam.</p>
            <p>Kira-kira pukul delapan malam, saat suasana rumah Tasya mulai agak tenang, ponsel Tasya yang diletakkan di atas meja ruang tamu bergetar. Sebuah pesan WhatsApp masuk dari Sakra.</p>
            <blockquote>
                <strong>Sakra:</strong> <em>“Sya... masih terjaga? Keluar teras sebentar dong. Ada yang mau diomongin.”</em>
            </blockquote>
            <p>Tasya yang sedang melipat mukena langsung bangkit, melangkah pelan membuka pintu depan, dan mendapati Sakra berdiri di dekat pagar halaman rumah lamanya dengan mengenakan jaket tipis.</p>
            <p>Setelah basa-basi sebentar dengan mengabaikan dinginnya angin malam Bandung, Sakra menatap Tasya dengan binar penuh harap di matanya. "Sya... besok lu ada acara keluarga gak dari pagi sampai siang?"</p>
            <p>Tasya menggeleng pelan. "Kayaknya nggak ada, Sak. Paling sorean mau silaturahmi ke rumah bibi. Emangnya kenapa?"</p>
            <p>"Besok... lu mau jalan berdua sama gua?" ajak Sakra spontan, nada suaranya terdengar antusias namun ada sedikit debar gugup di sana. "Cuma berdua. Kayak masa-masa dulu sebelum lu pindah ke Pangandaran. Gua pengen ngajak lu ke tempat-tempat favorit kita di Bandung, tanpa ada Trea, tanpa ada rombongan lain."</p>
            <p>Tasya menatap wajah Sakra lekat-lekat. Senyuman manis langsung terkembang di bibirnya. Tanpa butuh waktu lama untuk berpikir, ia mengangguk mantap. "Mau. Besok jemput gue pagi ya, Sak."</p>
            <p>Keesokan paginya, matahari Bandung menyapa dengan kehangatan yang pas. Hari itu murni milik mereka berdua.</p>
            <p>Sakra menepati janjinya. Mengendarai sepeda motor matik pinjaman dari Indra, ia membonceng Tasya membelah jalanan Bandung yang mulai lengang di hari kedua Lebaran. Mereka menghabiskan separuh hari dengan menyusuri nostalgia: mampir ke kedai es krim legendaris di Jalan Braga, berjalan-jalan santai di bawah rindangnya pohon-pohon tua di kawasan Cikini-nya Bandung, hingga menertawakan hal-hal konyol yang dulu sering mereka debatkan saat masih SMP.</p>
            <p>Menjelang sore hari, ketika cahaya matahari mulai meredup dan berubah jingga keemasan di ufuk barat, Sakra membawa Tasya naik ke dataran yang sedikit lebih tinggi—sebuah kawasan perbukitan di utara Bandung yang menawarkan pemandangan lanskap kota gemerlap dari kejauhan, jauh dari bisingnya kendaraan.</p>
            <p>Mereka memarkirkan motor di tepi jalan setapak yang dikelilingi pohon pinus, lalu duduk berdampingan di atas bangku kayu panjang yang menghadap langsung ke arah lembah Kota Bandung. Angin sore berhembus sepoi-sepoi, membawa hawa dingin pegunungan yang menusuk pori-pori, membuat Tasya sedikit merinding dan mengeratkan pelukan pada jaketnya sendiri.</p>
            <p>Melihat Tasya yang kedinginan, tanpa banyak bicara, Sakra langsung membuka jaket <em>hoodie</em> hitam yang ia kenakan rangkap di luar kemejanya, lalu menyampirkannya ke bahu Tasya dengan lembut.</p>
            <p>"Nih, pakai. Nanti lu masuk angin kalau nekat kedinginan begini," ujar Sakra perhatian.</p>
            <p>Tasya tersenyum kecil, menarik ritsleting jaket itu hingga pas menutupi dadanya. Aromanya sangat khas—aroma sabun cuci bercampur wangi tubuh Sakra yang seketika memberikan kehangatan instan.</p>
            <p>Mereka duduk terdiam sejenak, menikmati pemandangan kota yang mulai menyalakan lampu-lampu kecilnya satu persatu di kejauhan. Langit berubah dari jingga tua menjadi ungu gelap yang menenangkan. Jarak di antara mereka di atas bangku kayu itu begitu dekat, nyaris tanpa celah.</p>
            <p>Perlahan-lahan, beban emosional selama berbulan-bulan—mulai dari rasa cemburu buta, ancaman Bara, rasa <em>insecure</em>, hingga rasa bersalah karena jarak 179 kilometer—seolah melebur sirna ditiup angin sore. Yang tersisa hanyalah ketulusan sederhana dari dua remaja yang saling merindukan.</p>
            <p>Tanpa sadar, Tasya menggeser duduknya sedikit lebih dekat. Perlahan tapi pasti, kepala Tasya bergerak menyandarkan diri sepenuhnya ke atas bahu bidang Sakra. Ia memejamkan mata, meresapi setiap detik ketenangan yang sudah lama tidak ia rasakan.</p>
            <p>Sakra terkesiap kecil seketika saat beban lembut kepala Tasya menumpu di bahunya. Jantungnya langsung berdegup kencang bak ditabuh ribuan tabuh kendang. Namun, alih-alih merasa canggung, ia perlahan merilekskan tubuhnya. Sakra mengangkat tangan kanannya, merangkul bahu Tasya dengan hati-hati, lalu membiarkan kepala gadis itu bersandar dengan aman di sisinya.</p>
            <p>"Capek ya, Sya?" bisik Sakra sangat lembut, nyaris tenggelam oleh desau angin pinus.</p>
            <p>"Sedikit..." jawab Tasya pelan dengan mata tetap terpejam, suaranya terdengar sangat damai. "Tapi capeknya hilang pas bareng lu kayak gini, Sak."</p>
            <p>Sakra mengecup pucuk kepala Tasya sekilas dengan penuh kasih sayang, sementara tangan kirinya menggenggam jemari Tasya erat-erat di atas pangkuan. Di bawah langit senja Bandung yang saksi bisu, hari berdua itu membuktikan satu hal mutlak bagi mereka: seberat apa pun badai jarak dan rintangan yang pernah dan akan mereka hadapi di masa depan, selama mereka bisa duduk berdampingan seperti ini, segala lelah di dunia mendadak terasa layak untuk diperjuangkan.</p>
        `
    }
];
