
// File: data14.js
const novelData14 = [
    { 
        title: "Bab 16: Hari ke-132 — Rian dan Tuduhan yang Menyakitkan", 
        content: `
            <p>Udara pesisir Pangandaran pada siang itu terasa begitu lembap dan menyesakkan dada, seolah gumpalan mendung tipis di langit selatan sengaja menahan hawa panas agar tetap mengendap dan memanggang permukaan bumi. Di dalam kamarnya yang berantakan, Tasya terbaring lemah di atas kasur dengan selimut tebal bermotif floral menutupi sekujur tubuhnya yang menggigil kedinginan meskipun cuaca di luar terasa gerah. Wajahnya tampak pucat pasi, nyaris tanpa warna, bibirnya kering pecah-pecah akibat dehidrasi ringan, dan keningnya terasa sangat panas ketika tersentuh oleh punggung tangan.</p>
            <p>Diagnosis dari dokter klinik pratama di ujung jalan sudah jelas dan tidak terbantahkan: Tasya terserang penyakit tifus. Penyakit akut itu datang menyerang akibat akumulasi kelelahan fisik yang teramat sangat, pola makan yang berantakan selama berminggu-minggu, serta stres pikiran yang menguras energi mentalnya secara konstan dalam diam.</p>
            <p>Pintu kamarnya berderit pelan saat didorong dari luar. Ibu melangkah masuk dengan membawa nampan berisi semangkuk bubur hangat yang mengepulkan uap tipis dan segelas air putih hangat. Dengan penuh kelembutan yang menyiratkan kecemasan seorang ibu, beliau duduk di tepi ranjang, lalu membantu Tasya untuk sedikit mengangkat kepala dan bersandar pada bantal.</p>
            <p>"Makan sedikit ya, Sya... biar perutnya ada isi dan obat dari dokter bisa masuk dengan baik ke badan kamu," bujuk sang Ibu dengan suara parau penuh kekhawatiran.</p>
            <p>Tasya menggeleng lemah, kelopak matanya terasa sangat berat untuk dibuka. "Perut Tasya mual, Ma... gak sanggup nelan apa-apa," bisik Tasya lirih, suaranya nyaris hilang ditelan keheningan kamar. Ia hanya sanggup memakan dua sendok kecil bubur hambar sebelum rasa mual yang hebat kembali melilit dinding perutnya, memaksanya menggelengkan kepala tanda menyerah.</p>
            <p>Ibu menghela napas panjang, mengelus rambut kusam anaknya dengan penuh kasih sayang sebelum merapikan kembali selimut Tasya dan mengganti handuk kompres di keningnya.</p>
            <p>Menjelang sore hari, ketika jarum jam menunjuk pukul empat sore, bel rumah berbunyi nyaring dari arah depan. Rupanya beberapa teman seangkatan pengurus OSIS SMAN 81 Pangandaran datang menjenguk untuk melihat kondisi sekretaris mereka yang mendadak tumbang. Rian, sang Ketua OSIS yang berpostur tinggi tegap, memimpin rombongan kecil itu dengan membawakan sebungkus parsel buah-buahan segar serta setumpuk buku catatan materi sekolah yang tertinggal selama beberapa hari terakhir.</p>
            <p>Karena sudah dianggap akrab sebagai rekan kerja organisasi dan atas izin ibu Tasya yang membukakan pintu, Rian diperbolehkan masuk sebentar ke dekat pintu kamar untuk melihat kondisi Tasya secara langsung tanpa mengganggu waktu istirahatnya.</p>
            <p>"Gimana keadaan lu, Sya? Pucat banget sumpah, kayak mayat hidup," ujar Rian dari ambang pintu kamar dengan nada bercanda yang berusaha mencairkan suasana, meskipun sorot matanya menyiratkan rasa prihatin yang mendalam. "Makanya, kalau kerja organisasi jangan terlalu diforsir kayak mau kerja rodi. Nih, catatan materi ekonomi dan sosiologi kemarin udah gua fotokopiin segepok penuh, nanti dibaca kalau lu udah agak enakan."</p>
            <p>Tasya membuka matanya perlahan, menatap ke arah Rian yang berdiri di dekat lemari pakaian. "Makasih banyak ya, Rian... maaf banget jadi repotin kalian semua buat nengokin aku ke sini," jawab Tasya dengan suara serak yang parau.</p>
            <p>Rian dan teman-teman pengurus OSIS lainnya tidak tinggal terlalu lama. Mereka hanya menjenguk selama kurang lebih lima belas menit, memberikan doa kesembuhan agar Tasya bisa segera kembali aktif di sekolah, lalu pamit pulang agar gadis itu bisa kembali beristirahat secara total dalam keheningan.</p>
            <p>Namun, tanpa disadari oleh Tasya yang sudah terlampau lemas dan pusing untuk memegang ponsel atau memperhatikan sekitar, salah satu anggota junior OSIS sempat mengambil satu foto suasana saat mereka menjenguk dari jarak agak jauh—menampilkan Rian yang berdiri membawa kantong buah di dekat pintu kamar—lalu mengunggahnya ke status WhatsApp pribadi dengan <em>caption</em> doa singkat: <em>“Cepat sembuh ya Kak Tasya, dijenguk langsung sama Pak Ketos nih.”</em></p>
            <p><em>Dua jam kemudian, di Kota Bandung...</em></p>
            <p>Sakra sedang duduk terpaku di meja belajarnya yang diterangi pendar lampu meja berwarna kuning hangat. Di hadapannya, tumpukan modul kuliah dan lembar kerja program <em>web development</em> berserakan tak beraturan. Ia baru saja menyelesaikan kelas daring pertamanya sebagai mahasiswa baru, dan kini berniat melepas penat dengan membuka ponsel untuk melihat kabar dari kekasihnya di Pangandaran.</p>
            <p>Jempol Sakra menggeser layar aplikasi WhatsApp, membuka bagian <em>status</em> atau <em>story</em> dari beberapa kontak teman seangkatan Tasya yang tersimpan di ponselnya.</p>
            <p>Seketika itu juga, napas Sakra tertahan di tenggorokan.</p>
            <p>Matanya terbelalak menatap sebuah foto yang diunggah oleh salah satu anak SMAN 81 Pangandaran. Di dalam layar ponselnya terpampang jelas potret Rian—pemuda bertubuh tegap yang dulu sempat merangkul Tasya di hutan pinus—berdiri di dalam rumah Tasya, tepat di dekat pintu kamar tempat gadis itu berbaring sakit, membawa parsel buah dengan senyuman ramah.</p>
            <p>Darah Sakra mendidih seketika, melonjak naik dengan kecepatan penuh ke ubun-ubun.</p>
            <p>Seluruh trauma lama, rasa <em>insecure</em> yang selama ini dipendam rapat-rapat, bayangan cemburu di Jalan Braga, hingga rasa lelah akibat tekanan kuliah dan beban psikologis masa lalu meledak menjadi satu dalam gelombang amarah yang membabi buta. Akal sehatnya tertutup oleh kabut kecemburuan buta. Sakra tidak memikirkan fakta bahwa Tasya sedang terbaring sakit parah; di dalam kepalanya yang dikuasai ego toksik, yang ada hanyalah bayangan bahwa kekasihnya dikunjungi oleh lelaki lain di ruang paling privasi—kamar tidurnya.</p>
            <p>Tanpa menyaring emosinya sedikit pun, Sakra meraih ponsel pribadinya dengan tangan yang gemetar menahan geram, lalu mengetik pesan interogasi yang sangat tajam dan melukai ke nomor Tasya.</p>
            <blockquote>
                <strong>Sakra:</strong> <em>“Sya. Lagi sakit kenapa si Rian bisa ada di kamar lu? Kenapa lu segitunya bebas jenguk lu sampai ke dalam rumah? Lu gak pernah bilang kalau cowok itu bakal datang nyamperin lu ke kamar.”</em>
            </blockquote>
            <p>Di ujung selatan Jawa Barat, sejauh 179 kilometer dari Bandung, di dalam kamarnya yang sunyi dan remang, Tasya sedang berusaha keras memejamkan mata untuk meredakan denyut nyeri yang luar biasa di pelipisnya akibat demam tifus. Tiba-tiba, getaran panjang dari ponsel di samping bantal memecah kesunyian malam di kamarnya.</p>
            <p>Dengan mata yang berkunang-kunang dan kepala yang terasa berputar hebat, Tasya meraba meja kecil di samping kasur, meraih benda pipih tersebut, dan membuka aplikasi pesan.</p>
            <p>Begitu ia membaca rentetan kalimat bernada tuduhan, kecurigaan, dan interogasi dingin yang dikirimkan oleh Sakra, dada Tasya terasa dihantam oleh palu godam berukuran raksasa. Napasnya seketika sesak. Air mata panas yang selama ini ia tahan karena menahan sakit fisik di tubuhnya tumpah begitu saja membasahi pipinya yang sayu.</p>
            <p>Ia sedang berjuang melawan infeksi bakteri tifus yang membuat sekujur tubuhnya linu dan tak bertenaga, ia tidak bisa turun dari tempat tidur bahkan sekadar untuk ke kamar mandi sendiri, namun di saat-saat paling rentan dalam hidupnya, orang yang paling ia cintai dan harapkan kehadirannya justru datang membawa pisau penghakiman yang menusuk jantungnya.</p>
            <p>Dengan jari-jemari yang lemas dan bergetar hebat menahan isak tangis, Tasya mengetik balasan penuh kepedihan yang teramat sangat:</p>
            <blockquote>
                <strong>Tasya:</strong> <em>“Lu tega banget, Sak... Aku lagi sakit tifus parah, lemas, gak bisa bangun dari kasur seharian, tapi yang pertama kali lu tanyain malah nuduh aku yang aneh-aneh soal Rian. Kenapa... kenapa lu gak pernah bisa percaya sama aku sedikit aja...?”</em>
            </blockquote>
            <p>Di kamarnya di Bandung, Sakra—yang masih dikuasai oleh sisa-sisa amarah dan ego kekanak-kanakannya—alih-alih melunak atau meminta maaf setelah tahu Tasya sakit parah, justru membalas dengan nada dingin yang semakin menyayat hati:</p>
            <blockquote>
                <strong>Sakra:</strong> <em>“Bukannya gak percaya, Sya. Tapi posisi dia di foto itu terlalu bebas masuk ke area pribadi lu. Sebagai cowok lu, wajar kan kalau gua ngerasa terganggu?”</em>
            </blockquote>
            <p>Melihat balasan dingin dan keras kepala itu, pertahanan terakhir Tasya runtuh berkeping-keping. Isak tangisnya pecah menjadi jeritan tertahan yang memecah kesunyian malam di kamarnya. Ia memeluk guling erat-erat, meredam suaranya agar tidak terdengar oleh ibu di luar kamar, sementara air matanya mengalir deras tanpa henti, membasahi sarung bantal hingga basah kuyup.</p>
            <p>Rasa sakit di sekujur tubuhnya akibat tifus kini terasa tidak ada apa-apanya dibandingkan rasa hancur di dalam dadanya. Sakra telah melukai harga dirinya di saat ia berada di titik terlemah dalam hidupnya.</p>
            <p>Sudah tidak ada lagi tenaga yang tersisa di tubuh Tasya untuk mengetik balasan atau berdebat membela diri. Dalam kondisi demam tinggi yang membuat kesadarannya mulai melayang dan hati yang tercabik-cabik, Tasya meraba ponselnya sekali lagi dengan sisa-sisa tenaga yang ia miliki. Ia mencari satu nama kontak darurat yang selalu siap sedia merengkuhnya di saat-saat hancur seperti ini.</p>
            <p><em>Trea.</em></p>
            <p>Tasya menekan tombol panggilan suara ke nomor Trea. Begitu sambungan terhubung di dering pertama, tangis histeris Tasya langsung pecah tanpa bisa dikendalikan lagi di ujung telepon.</p>
            <p>"Tre... hiks... Trea..." tangis Tasya tersenggal-senggal di kamarnya di Pangandaran, suaranya nyaris tak berbentuk karena kehabisan napas. "Sakra jahat banget, Tre... aku lagi sakit, aku lagi sakaratul maut di kasur... tapi dia malah nuduh aku yang bukan-bukan cuma karena anak-anak OSIS jenguk ke rumah..."</p>
            <p>Di kamarnya di Bandung, Trea yang sedang bersiap tidur mendadak terperanjat kaget mendengar histerisnya tangisan sahabat karibnya dari ujung kabupaten. Alis Trea bertaut tajam, sorot matanya berubah menjadi kemarahan yang menyala-nyala. Sebagai orang yang paling mengerti betapa besar pengorbanan batin Tasya selama ini, kemarahan Trea memuncak pada kebodohan Sakra.</p>
            <p>"Sialan emang si Sakra..." gumam Trea penuh geram di kamarnya, mengepalkan tangan kanannya erat-erat. "Bisa-bisa nya dia nyakitin Tasya pas anak itu lagi terkapar sakit. Awas aja, keterlaluan banget ego cowok itu!"</p>
            <p>Malam di Hari ke-132 itu berubah menjadi malam paling kelam dalam sejarah hubungan mereka. Jarak 179 kilometer tidak lagi sekadar angka di atas peta, melainkan sebuah jarak pemisah yang memperparah kesalahpahaman, mengubah kecemburuan kecil menjadi bara api yang membakar hangus seluruh kepercayaan yang telah mereka bangun susah payah dari reruntuhan masa lalu.</p>
        `
    }
];
