// File: data3.js
const novelData3 = [
    { 
        title: "Bab 5: Hari ke-60 — Antara Hutan Pinus Dan Braga", 
        content: `
            <p>Malam di Jalan Braga, Bandung, selalu menawarkan riuhnya suasana yang membius siapa saja yang melangkah di atas trotoarnya. Pukul delapan malam, kawasan bersejarah itu dipadati oleh muda-mudi yang menikmati udara dingin kota kembang di bawah temaram lampu jalan bergaya kolonial yang memancarkan cahaya kuning hangat. Suara petikan gitar akustik dari para pengamen jalanan yang membawakan lagu-lagu indie lokal berpadu dengan deru kendaraan bermotor yang melintas pelan, menciptakan melodi urban yang sangat khas—deru bising kota yang malam itu terasa begitu kontras dengan keheningan mencekam di dalam kepala Sakra.</p>
            <p>Namun, di salah satu sudut meja kedai kopi terbuka beratap payung kanvas besar di pinggir jalan, Sakra sama sekali tidak menikmati suasana tersebut.</p>
            <p>Ia duduk membungkuk di kursi kayu berpelitur gelap, kedua sikunya menumpu di atas meja kecil yang permukaannya lengket oleh sisa tumpahan gula. Sementara jemarinya mencengkeram erat bodi ponsel pintar yang layarnya menyala terang, memantulkan cahaya putih kebiruan langsung ke wajahnya yang tampak kuyu dan kehilangan warna. Di hadapannya, Indra dan Habib sedang asyik menyeruput es americano pesanan mereka sambil membicarakan rencana <em>touring</em> motor matik akhir pekan depan ke kawasan pegunungan Lembang.</p>
            <p>"Gimana, Kra? Lu jadi ikut <em>touring</em> minggu depan? Biar otak lu gak korslet melulu gara-gara ngebanting tulang ngurusin kodingan server sama data MDC Pramuka yang seabrek itu," tanya Indra tanpa mengalihkan pandangannya dari layar ponsel yang menampilkan rute peta jalan raya.</p>
            <p>Sakra tidak menjawab sepatah kata pun. Ia bahkan tidak mendengarkan ucapan Indra sedikit pun. Seluruh indranya, kesadarannya, dan detak jantungnya terkunci mati pada satu objek tunggal di dalam layar ponselnya. Matanya terbelalak menatap satu foto terbaru yang baru saja diunggah ke <em>story</em> WhatsApp oleh salah satu teman seangkatan Tasya di SMAN 81 Pangandaran.</p>
            <p>Foto itu diambil dengan latar belakang kabut sore yang tebal di kawasan wisata alam perbukitan Pangandaran. Di tengah kabut tipis yang menyelimuti dan deretan pohon pinus yang menjulang tinggi, Tasya tampak berdiri tersenyum lebar bersama sekelompok anak OSIS yang mengenakan jaket <em>outdoor</em> seragam organisasi. Dan yang membuat dada Sakra mendadak sesak seolah dihantam palu godam berukuran besar: tepat di samping Tasya, berdiri Rian—sang Ketua OSIS SMAN 81—dengan jaket denim yang merangkul setengah bahu Tasya dalam pose akrab kelompok remaja yang sedang menikmati liburan akhir pekan bersama di alam bebas.</p>
            <p><em>Buzzz... Buzzz...</em></p>
            <p>Ponsel Sakra bergetar pelan di dalam genggamannya yang kaku. Sebuah pesan masuk dari Tasya, memecah lamunannya yang kelam dan penuh amarah.</p>
            <blockquote>
                <strong>Tasya:</strong> <em>“Sak... maaf ya baru ngabari sekarang. Tadi sore anak-anak OSIS ngajak jalan dadakan ke bukit pinus dekat pantai buat refreshing melepas penat proposal pentas seni kemarin. Sinyal di sini jelek banget, baru dapet WiFi kafe nih.”</em>
            </blockquote>
            <p>Sakra membaca pesan itu dengan rahang mengeras hingga giginya bergemeretup keras. Rasa cemburu yang membakar lambungnya bercampur aduk secara destruktif dengan rasa lelah akibat kurang tidur selama berminggu-minggu, ditambah tumpukan tugas sekolah yang mulai terbengkalai. Posisinya yang terjebak di Bandung membuatnya merasa sangat tidak berdaya, terkurung, dan terisolasi. Ia tidak bisa datang ke sana, tidak bisa merangkul Tasya untuk memastikan posisinya aman, dan hanya bisa menjadi penonton pasif dari layar kaca berukuran enam inci yang dingin di hadapannya.</p>
            <p>Tanpa sadar, dipicu oleh emosi yang meluap-luap tanpa saringan logika, jemari Sakra mengetik balasan dengan nada protektif yang tajam, menghakimi, dan menusuk.</p>
            <blockquote>
                <strong>Sakra:</strong> <em>“Ramai banget kayaknya. Itu si Rian ngapain dekat-dekat banget posisinya di foto? Kenapa gak bilang dari awal kalau mau pergi bareng cowok itu?”</em>
            </blockquote>
            <p>Beberapa detik berlalu dalam keheningan yang menyesakkan dada. Pesan Sakra hanya berdering centang dua abu-abu. Tasya belum membalasnya. Waktu berjalan terasa begitu lambat, merayap bagai siput di atas kaca jendela yang basah. Setiap detik penantian membuat emosi Sakra semakin tidak terkontrol. Bayangan Rian yang berdiri dekat dengan Tasya terus berputar-putar di kepalanya, memicu rasa <em>insecure</em> akut yang mengakar kuat dari jarak 179 kilometer di antara mereka.</p>
            <p>"Kra? Lu kenapa mukanya ditekuk begitu dari tadi? Kayak orang punya utang belum dibayar setahun," tegur Habib, menyadari perubahan drastis pada gestur tubuh Sakra yang menegang kaku seperti patung.</p>
            <p>"Gak apa-apa," jawab Sakra dingin, suaranya terdengar tertahan di tenggorokan, berat dan parau.</p>
            <p>"Gak apa-apa gimana, muka lu merah padam begitu. Lu cemburu ya liat foto anak Pangandaran?" celoteh Indra asal, menebak tepat di sasaran tanpa tahu seberapa sensitif dan rapuhnya topik itu bagi Sakra malam ini. "Udah lah, Kra. Namanya juga anak sekolah di sana, wajar kalau bergaul dalam kelompok. Kalau lu begini terus, lu bakal jantungan sendiri di Bandung."</p>
            <p>Nasihat Indra alih-alih menenangkan gemuruh di dada Sakra, justru membuat pemuda itu semakin tersulut. Rasa tidak aman yang terpendam akibat jarak fisik yang membentang jauh meledak menjadi sikap posesif yang tidak sehat—sebuah bentuk kekhawatiran berlebihan yang mulai berubah menjadi racun dalam hubungan mereka.</p>
            <p>Sejauh 179 kilometer ke arah tenggara, di sebuah sudut kafe pesisir Pangandaran yang bising oleh suara obrolan pengunjung lain, Tasya menatap layar ponselnya dengan hati yang mencelos sakit. Di saat ia baru saja ingin menikmati sedikit udara segar setelah berminggu-minggu terkuras tenaganya demi urusan sekolah dan tekanan OSIS, Sakra justru menyambutnya dengan kecurigaan dan interogasi yang menyudutkan seolah ia melakukan kesalahan besar. Air mata Tasya langsung menggenang di pelupuk matanya, panas, sesak, dan tak tertahankan.</p>
            <blockquote>
                <strong>Tasya:</strong> <em>“Kok lu jadi nuduh gitu sih, Sak? Itu cuma foto bareng-bareng anak OSIS, gak sengaja dempetan pas angin kencang di bukit. Kenapa lu jadi posesif banget belakangan ini, sih?”</em>
            </blockquote>
            <p>Melihat balasan itu, alih-alih melunak dan meminta maaf atas sikap kasarnya, ego Sakra yang diselimuti kelelahan kronis semakin menguasai akal sehatnya. Ia merasa Tasya tidak menghargai kecemasan dan pengorbanan batin yang ia pertaruhkan selama ini di Bandung.</p>
            <blockquote>
                <strong>Sakra:</strong> <em>“Terserah lu mau bilang apa. Yang jelas tiap kali lu jalan sama dia, lu selalu nutupin dari gue.”</em>
            </blockquote>
            <p>Setelah mengirim kalimat telak yang melukai itu, Sakra langsung menekan tombol pengaturan dan mematikan data selulernya secara paksa. Layar ponselnya gelap gulita seketika. Ia melempar benda pipih itu dengan kasar ke atas meja kedai kopi Braga, membuat Indra dan Habib terperanjat kaget hingga es americano mereka tumpah sedikit ke atas piring kecil tempat cangkir diletakkan.</p>
            <p>"Waduh, ngamuk beneran anak ini. Ada angin apa sih, Kra? Jangan bikin ngeri deh," gumam Habib geleng-geleng kepala, menatap ponsel Sakra yang tergeletak pasrah di tengah meja.</p>
            <p>Sakra menatap lampu-lampu kota Bandung yang berpendar indah di sepanjang Jalan Braga dengan hati yang hancur berkeping-keping. Di malam yang dingin itu, di bawah temaram lampu kolonial yang menjadi saksi bisu, ia baru saja menyadari bahwa jarak 179 kilometer bukan lagi sekadar masalah angka di peta atau lamanya perjalanan bus antar-wilayah, melainkan sebuah jurang miskomunikasi yang mulai merusak fondasi hubungan mereka dari dalam.</p>
            <p>Dan dari balik layar monitor kamarnya nanti malam, di tengah keheningan kamar yang ditemani dengung kipas <em>cooling pad</em> laptop, Sakra bertekad untuk melakukan sesuatu yang jauh lebih besar—sebuah proyek digital masif yang ia harapkan bisa mengunci hati Tasya selamanya, tanpa ia sadari bahwa proyek ambisius itu justru akan menjadi beban psikologis paling berat yang kelak mencekik napas sang kekasih.</p>
        `
    }
];
