// File: data12.js
const novelData12 = [
    { 
        title: "Bab 14: Hari ke-135 — Riak Kecil", 
        content: `
            <p>Dua minggu telah berlalu sejak malam di mana tautan <em>Project_179</em> dikirimkan dan meruntuhkan pertahanan air mata Tasya di Pangandaran. Situs web interaktif itu kini menjadi semacam tempat suci digital bagi hubungan mereka. Setiap kali rasa sepi atau penat akibat jarak 179 kilometer menghantam, Tasya mengaku sering membuka kembali tautan tersebut hanya untuk mendengarkan rekaman suara tawanya sendiri yang disembunyikan Sakra di balik barisan kode galaksi malam.</p>
            <p>Di Bandung, Sakra menjalani hari-harinya dengan ritme yang jauh lebih sehat. Ia menepati janjinya pada sang ibu, pada Trea, dan terutama pada Tasya. Tidak ada lagi begadang semalaman buta untuk melayani klien joki game yang toksik. Tidak ada lagi tubuh yang ambruk karena memforsir diri melampaui batas kewajaran. Ia kembali fokus pada rutinitasnya sebagai siswa tingkat akhir di SMAN 90 Bandung, merapikan nilai-nilai pelajarannya yang sempat keteteran, serta mengurus kegiatan MDC Pramuka dengan porsi yang wajar dan terukur.</p>
            <p>Namun, di balik ketenangan permukaan yang berhasil mereka bangun, sebuah riak kecil yang tak terduga mulai muncul dari arah yang sama sekali tidak mereka sangka-sangka.</p>
            <p>Hari itu, matahari sore bersinar hangat memantulkan cahaya keemasan di halaman depan SMAN 81 Pangandaran. Jam pelajaran telah berakhir sejak sepuluh menit lalu, namun Tasya masih harus tinggal di ruang sekretariat OSIS untuk merapikan beberapa berkas laporan pertanggungjawaban kegiatan bazar seni yang baru saja selesai disetujui pembina.</p>
            <p>Di ruang sebelah meja kerjanya, Rian—sang Ketua OSIS yang berpostur tinggi tegap—tampak sedang membereskan setumpuk poster promosi acara amal bulan depan. Tanpa sengaja, pandangan Rian tertuju ke arah layar monitor laptop Tasya yang kebetulan sedang menyala, menampilkan jendela peramban dengan latar belakang galaksi ungu gelap dan teks bertuliskan koordinat <em>Bandung - Pangandaran: 179 km</em>.</p>
            <p>Rian mengerjap-ngerjap, lalu melangkah mendekat dengan rasa penasaran yang wajar. "Eh, Sya? Ini web apa yang lu buka dari tadi? Keren banget desainnya, kayak game sci-fi atau web portfolio profesional. Siapa yang bikin? Lucu ada animasi garis jarak Bandung-Pangandaran gitu."</p>
            <p>Tasya yang tadinya sedang fokus menulis rekapitulasi data spontan terperanjat kaget. Ia buru-buru menutup tab peramban tersebut hingga layar laptopnya kembali menampilkan desktop utama. Pipinya mendadak merona merah, antara salah tingkah dan merasa privasinya tiba-tiba tersentuh.</p>
            <p>"Ah... eh, bukan apa-apa, Rian! Cuma... proyek iseng web pribadi doang buat tugas," jawab Tasya sedikit gagap, mencoba menutupi gugupnya dengan merapikan tumpukan kertas di hadapannya.</p>
            <p>Rian terkekeh pelan, mengangkat kedua tangannya ke udara tanda menyerah. "Wah, santai kali, Sya. Gua kan cuma nanya, gak bermaksud nyelonong privasi lu. Tapi jujur, desainnya rapi banget. Kalau lu jago koding gitu, kenapa gak coba didaftarin buat lomba web design antarsekolah bulan depan? Lumayan tuh nambah sertifikat prestasi."</p>
            <p>"Makasih sarannya, tapi emang bukan gue yang bikin kok," elak Tasya cepat, berusaha mengalihkan pembicaraan agar Rian tidak bertanya lebih jauh mengenai <em>Project_179</em> yang merupakan ranah paling privasi antara dirinya dan Sakra.</p>
            <p>Meskipun percakapan itu berlalu begitu saja dan Rian kembali sibuk dengan urusannya, sebuah insiden kecil di ruang OSIS itu ternyata meninggalkan jejak digital yang tidak disengaja. Tanpa Tasya sadari, riwayat pencarian peramban di laptop pinjaman OSIS tersebut sempat merekam cache tautan publik GitHub milik Sakra.</p>
            <p>Dan sialnya, beberapa hari kemudian, salah satu junior pengurus OSIS yang meminjam laptop yang sama untuk keperluan mencetak surat melihat riwayat tautan tersebut, membukanya <em>out of curiosity</em>, lalu menyebarkannya ke dalam grup WhatsApp internal pengurus inti OSIS sebagai bahan candaan ringan.</p>
            <blockquote>
                <em>“Eh, liat deh link web ini. Lucu banget, kayak surat cinta online anak IT. Ada angka 179 km segala, mirip jarak Bandung-Pangandaran. Jangan-jangan buatan pacarnya Kak Tasya yang di Bandung ya?”</em>
            </blockquote>
            <p>Candaan di grup internal itu menyebar cepat layaknya api sekam di kalangan anak-anak OSIS SMAN 81 Pangandaran. Hingga akhirnya, pada suatu siang di kantin sekolah, salah satu teman angkatan Tasya secara terang-terangan menggoda Tasya di hadapan banyak orang.</p>
            <p>"Sya! Ngaku lu, ya! Lu dibikinin web romantis khusus sama pacar lu yang di Bandung, kan? Anak-anak OSIS pada ngeliat history link di laptop kemarin!" seru seorang teman perempuan Tasya sambil tertawa-tawa usil di meja kantin.</p>
            <p>Tasya yang sedang memegang gelas es teh manis mendadak tersedak ludahnya sendiri. Ia batuk-batuk kecil, sementara wajahnya berubah menjadi merah padam menahan malu. Di satu sisi, ia merasa bangga dan tersanjung setengah mati atas karya luar biasa yang dipersembahkan Sakra khusus untuknya. Namun di sisi lain, sifat introver Tasya sangat membenci ketika kehidupan percintaannya yang sakral dan penuh perjuangan LDR itu harus menjadi konsumsi publik atau bahan gosip anak-anak sekolah.</p>
            <p>Rasa risih dan gelisah itu langsung membuncah di dalam dada Tasya. Sore harinya, begitu ia tiba di kamar kosnya, ia langsung meraih ponsel dan melancarkan protes kecil lewat pesan WhatsApp kepada Sakra di Bandung.</p>
            <blockquote>
                <strong>Tasya:</strong> <em>“Sak... lu jahat ih! Kenapa sih bikin web Project_179 itu pakai domain publik GitHub yang gampang banget diakses orang lain? Tahu gak, kemarin anak-anak OSIS di sekolah gak sengaja nemu history-nya di laptop kantor, terus sekarang jadi bahan gosip satu angkatan!”</em>
            </blockquote>
            <p>Di kamarnya di Bandung, Sakra yang sedang membaca buku catatan kuliah mendadak tertegun begitu membaca rentetan pesan dari Tasya. Senyuman di wajahnya perlahan memudar, digantikan oleh rasa bersalah yang mendadak muncul mencubit ulu hatinya.</p>
            <p>Sakra memang sengaja merilisnya secara publik di GitHub agar web itu bisa diakses dengan mudah tanpa harus repot mengatur server pribadi. Ia tidak pernah memperhitungkan kemungkinan kecil bahwa tautan itu bisa ditemukan dan dibicarakan oleh orang-orang di lingkungan sekolah Tasya yang sensitif terhadap gosip percintaan remaja.</p>
            <p>Sakra segera mengetik balasan dengan jempol yang sedikit ragu-ragu.</p>
            <blockquote>
                <strong>Sakra:</strong> <em>“Ya ampun, Sya... sumpah, gue beneran gak ada niat buat bikin web itu jadi konsumsi publik atau bahan gosip anak-anak sekolah lu. Gue cuma pakai GitHub karena itu cara paling gampang buat hosting web gratis tanpa ribet bayar domain. Maaf ya, Sya... kalau hal itu malah bikin lu gak nyaman di sana.”</em>
            </blockquote>
            <p>Di seberang sana, Tasya menatap layar ponselnya cukup lama. Kemarahan kecil yang tadinya sempat tersulut di hatinya perlahan-lahan melunak saat membaca kejujuran dan nada penyesalan yang tulus dari tulisan Sakra. Tasya sadar, Sakra melakukan itu murni karena cinta dan niat ingin membahagiakannya, sama sekali bukan untuk pamer atau mencari perhatian orang lain.</p>
            <p>Ia menghela napas panjang, lalu mengetik balasan bernada pasrah namun tetap manja.</p>
            <blockquote>
                <strong>Tasya:</strong> <em>“Iya sih, gue tahu lu gak ada maksud jelek... cuma kan malu tahu, dibicarain anak-anak sekolahan kayak gitu. Rasanya kayak privasi kita diintip orang banyak. Janji ya besok-besok kalau mau bikin kejutan jangan yang bikin gue jadi pusat perhatian seantero sekolah lagi?”</em><br><br>
                <strong>Sakra:</strong> <em>“Siap, laksanakan, Inces Pangandaran! Besok-besok gue kunci enkripsi web-nya pakai password tanggal jadian kita biar gak bakal bisa dibuka orang lain lagi, hahaha.”</em>
            </blockquote>
            <p>Membaca balasan jenaka Sakra, ketegangan di wajah Tasya akhirnya mencair. Bibirnya kembali mengukir senyuman tipis. Riak kecil berupa gosip sekolah itu berhasil mereka redam dengan komunikasi yang dewasa dan terbuka, membuktikan bahwa komunikasi mereka kini jauh lebih kuat dibandingkan saat insiden cemburu di Jalan Braga beberapa waktu lalu.</p>
            <p>Namun, di balik layar ketenangan malam itu, Sakra dan Tasya sama-sama menyadari satu kenyataan mutlak yang tidak bisa dihindari selamanya: hubungan jarak jauh sejauh 179 kilometer ini tidak akan pernah cukup jika hanya dirawat lewat layar kaca, barisan kode digital, atau sambungan telepon tengah malam. Suatu hari nanti, di masa depan yang tidak terlalu jauh, mereka harus mengambil keputusan besar untuk meruntuhkan jarak itu untuk selama-lamanya. Dan malam di Hari ke-135 itu menjadi saksi bisu bagaimana ujian-ujian kecil justru semakin mematangkan kedewasaan cinta di antara dua remaja yang terpisah kabupaten tersebut.</p>
        `
    }
];
