// File: data13.js
const novelData13 = [
    { 
        title: "Bab 15: Hari ke-150 — Keputusan di Persimpangan", 
        content: `
            <p>Waktu berputar tanpa pernah meminta izin untuk berhenti barang sekadar sedetik. Tanpa terasa, lembaran kalender kehidupan Sakra dan Tasya kini telah menginjak Hari ke-150. Udara Kota Bandung di penghujung bulan Mei mulai menyambut musim kemarau dengan hembusan angin pagi yang terasa lebih kering, namun langitnya membentang bersih tanpa cela.</p>
            <p>Di SMAN 90 Bandung, suasana di koridor kelas XII sudah lama tenggelam dalam euforia kelulusan. Papan pengumuman kelulusan baru saja ditempel di dekat ruang guru seminggu yang lalu, dan nama Sakra Sirotunawal tertera sah sebagai siswa yang lulus dengan predikat memuaskan, meski sempat terseok-seok akibat masalah kesehatan dan urusan joki game di pertengahan semester. Seragam putih abu-abu yang dulu sering dicoret-coret dengan spidol kini disimpan rapi di dalam lemari sebagai kenang-kenangan masa remaja yang penuh peluh dan air mata.</p>
            <p>Namun, di balik kelegaan status kelulusan tersebut, sebuah kenyataan baru yang jauh lebih menuntut mental dan kedewasaan mendadak hadir di hadapan Sakra: persimpangan jalan masa depan.</p>
            <p>Pagi itu, Sakra duduk di bangku taman kota dekat sekolahnya bersama Indra dan Habib. Di hadapan mereka terbentang brosur-brosur pendaftaran perguruan tinggi swasta serta seleksi masuk universitas negeri jalur mandiri.</p>
            <p>"Lu beneran gak mau nyoba ambil kuliah di luar kota, Kra? Misalnya merantau ke Jakarta atau Jogja sekalian?" tanya Indra sambil menyesap es teh manis kotaknya, menatap sahabat karibnya lekat-lekat.</p>
            <p>Sakra menggeleng pelan, pandangannya menerawang menatap lalu-lalang kendaraan di jalan raya. "Gak, Ndra. Keadaan ekonomi keluarga gua gak memungkinkan buat ngebiayain hidup merantau jauh. Mama sendirian di rumah, dan abang gua juga lagi sibuk merintis kerjaan di Bandung. Gua mutusin buat kuliah di kampus swasta lokal sini aja sambil kerja paruh waktu atau lanjutin proyek web <em>freelance</em>."</p>
            <p>"Tapi resikonya, lu tetep bakal sibuk setengah mati," timpal Habib mengingatkan. "Belum lagi urusan lu sama si Tasya di Pangandaran. Tasya kan masih kelas sebelas, tahun depan dia baru lulus SMA. Artinya, hubungan LDR kalian ini masih harus lanjut minimal satu setengah tahun lagi dengan status lu yang udah jadi mahasiswa."</p>
            <p>Kalimat Habib mendarat telak di kepala Sakra, memicu keheningan panjang di antara mereka bertiga.</p>
            <p>Selama ini, fokus mereka berdua selalu tersita pada bagaimana cara bertahan melewati hari-hari sekolah menengah—berjuang melawan badai tugas MDC, ancaman Bara, rasa <em>insecure</em>, hingga kolapsnya fisik Sakra di ruang UKS. Namun, mereka jarang mendiskusikan apa yang akan terjadi ketika garis waktu mulai bergerak maju ke fase dewasa: ketika Sakra melangkah masuk dunia perkuliahan, sementara Tasya masih harus menyelesaikan tahun terakhir masa putih abu-abunya di SMAN 81 Pangandaran.</p>
            <p>Jarak 179 kilometer itu tidak serta-merta menyusut; ia justru berpotensi melebar seiring bertambahnya kesibukan dan perbedaan dunia yang mereka pijak.</p>
            <p>Sejauh 179 kilometer ke arah tenggara, di ruang perpustakaan SMAN 81 Pangandaran, Tasya sedang merenungkan kekhawatiran yang serupa. Ia baru saja menyelesaikan ujian kenaikan kelas menuju kelas XII. Di atas meja belajarnya, buku catatan harian terselip di samping sebuah map berisi lembaran brosur kampus impian yang berada di Bandung—kota tempat Sakra berada sekarang.</p>
            <p>Tasya menyadari sepenuhnya bahwa tahun depan adalah gilirannya menghadapi ujian kelulusan nasional dan persaingan ketat masuk perguruan tinggi. Di dalam hatinya, tersimpan sebuah impian besar yang sudah lama ia pendam: ia ingin melanjutkan kuliah di Bandung agar tidak perlu lagi terpisah jarak sejauh 179 kilometer dengan Sakra. Ia ingin berdiri di kota yang sama, menghirup udara yang sama, dan mengakhiri siklus rindu lewat layar ponsel yang melelahkan ini.</p>
            <p>Namun, di waktu yang sama, bayangan akan realita ekonomi keluarganya dan ekspektasi orang tuanya membuat Tasya merasa tertekan. Apakah ia sanggup memperjuangkan impian itu tanpa membebani kedua orang tuanya? Dan yang lebih penting lagi, apakah hubungan mereka cukup kuat untuk menahan guncangan transisi dari masa remaja menuju usia dewasa muda?</p>
            <p>Malam harinya, pukul sembilan malam, Sakra dan Tasya melakukan panggilan video seperti biasa.</p>
            <p>Layar ponsel membagi wajah mereka berdua dalam satu bingkai digital. Setelah beberapa menit saling melempar senyum dan menceritakan kegiatan hari itu—Sakra dengan kesibukan pendaftaran kuliahnya, dan Tasya dengan persiapan liburan kenaikan kelasnya—suasana di antara mereka perlahan-lahan meredup menjadi keheningan yang sarat akan makna.</p>
            <p>Tasya menunduk sejenak, memainkan ujung kerudungnya, sebelum akhirnya mengangkat wajah menatap lekat-lekat mata Sakra di layar.</p>
            <p>"Sak..." panggil Tasya pelan, suaranya terdengar ragu-ragu namun serius.</p>
            <p>"Hm? Ada apa, Sya? Kenapa mukanya serius banget gitu?" tanya Sakra lembut, menyadari perubahan gestur kekasihnya.</p>
            <p>Tasya menarik napas dalam-dalam, mencoba mengumpulkan keberanian yang tersisa di dadanya. "Tadi siang... mama ngajak ngobrol soal rencana kuliah tahun depan pas aku lulus. Mama bilang, kalau bisa aku nyari kampus di sekitar Jawa Barat aja yang gak terlalu jauh dari keluarga."</p>
            <p>Jantung Sakra berdegup sedikit lebih kencang mendengarnya. Ia menunggu kelanjutan kalimat Tasya.</p>
            <p>"Dan... di dalam hati kecil aku, jujur aku pengen banget bisa kuliah di Bandung, Sak," lanjut Tasya, suaranya bergetar tipis sarat akan pengharapan. "Bukan cuma karena kotanya bagus, tapi... karena aku pengen kita gak terpisah jarak lagi. Aku capek LDR, Sak. Aku capek tiap malam harus nahan rindu lewat layar HP pas liat temen-temenku di sini bisa jalan bareng pacar mereka setiap akhir pekan."</p>
            <p>Pengakuan jujur yang terlontar langsung dari bibir Tasya itu menghantam dada Sakra dengan gelombang kehangatan sekaligus rasa tanggung jawab yang amat besar. Sakra tahu persis betapa tersiksanya Tasya menahan rindu selama ini di Pangandaran, sama persis seperti yang ia rasakan di Bandung.</p>
            <p>Sakra tersenyum teduh. Ia menyandarkan dagunya di atas tangan yang bertumpu pada meja belajar, menatap manik mata Tasya di layar dengan penuh keyakinan.</p>
            <p>"Sya... dengerin aku," ucap Sakra mantap, nada suaranya terdengar sangat tenang namun berbobot dewasa. "Kalau emang itu impian lu, kejar. Belajar yang bener buat tahun depan. Soal jarak... lu gak usah khawatir berlebihan. Kita udah ngelewatin 150 hari tersulit di awal hubungan kita—mulai dari badai, cemburu, penipuan, sampai kita berdua sama-sama tumbang masuk rumah sakit."</p>
            <p>Sakra menjeda kalimatnya sejenak, menarik napas panjang sebelum memberikan kalimat penutup yang merangkum seluruh ketulusan hatinya.</p>
            <p>"Kalau jarak 179 kilometer aja gak sanggup misahin kita kemarin, apalagi cuma sekadar transisi kuliah nanti. Apapun pilihan lu ke depan, aku bakal ada di sini, nunggu lu di Bandung, dan ngerayain hari di mana kita bener-bener bisa bebas pelukan tanpa harus mikirin kapan harus pisah stasiun lagi."</p>
            <p>Mendengar janji yang diucapkan Sakra dengan begitu tulus, air mata kebahagiaan menetes perlahan di pipi Tasya. Di kamar kosnya yang sunyi di Pangandaran, ia mengangguk perlahan sambil tersenyum lebar.</p>
            <p>Di Hari ke-150 itu, di ambang pintu gerbang kedewasaan yang penuh ketidakpastian, Sakra dan Tasya mengambil sebuah keputusan besar di persimpangan jalan: bahwa cinta mereka tidak lagi sekadar tentang pelarian remaja yang labil, melainkan sebuah komitmen sadar untuk terus berjalan ke arah yang sama, meruntuhkan jarak demi jarak, hingga akhirnya semesta benar-benar menyerah pada kesetiaan mereka.</p>
        `
    }
];
